### ISSUE TITLE
Fix line-height for image text block 

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#1013]
Please lower the line-height of the image text block items to something like 1.3em. Please give the items some margin in between. 
![bildschirmfoto 2017-12-04 um 20 36 33](https://user-images.githubusercontent.com/15341015/33572400-22db2d48-d933-11e7-8be1-f53e8ef7e429.png)

https://opin.me/en/start-your-project/

**Comment by rmader** [comment]
Should be fixed by #1017
