### ISSUE TITLE
404 error when trying to vote

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#1025]
We found a pretty critical error on the summit. When you try to vote but are not logged in, you get a 404 error instead of being taken to the login/register form.

**Comment by rittermo** [comment]
Might be connected https://github.com/liqd/a4-opin/issues/1024

**Comment by slomo** [comment]
I can reproduce the behaviour from #1024 and there is a story in out backlog to fix this. But I can't reproduce what you describe.

**Comment by rmader** [comment]
Just tested and voting was not clickable when logged out
