### ISSUE TITLE
styling of accordeon looks broken

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1087]
There is always an "x" behind the title I typed in. 
The arrow to open and close the accordeon is missing. 
It is in general very blue..

![screen shot 2018-02-07 at 12 20 29](https://user-images.githubusercontent.com/15954895/35913849-66c765f2-0c01-11e8-97b2-0444108a7e74.png)

**Comment by mkind** [comment]
looks fine for me. maybe caching issues?

**Comment by gereonrahnfeld** [comment]
you are right - works well after re-freshing. sorry again. will close.
