### ISSUE TITLE
Cannot leave comments in processes

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1088]
check for example the project: dst by oGGRahnfeld 
I cannot comment on the proposal dfgd because the comment field is not there.

![screen shot 2018-02-07 at 12 24 42](https://user-images.githubusercontent.com/15954895/35914030-108ee498-0c02-11e8-8995-4c217b595905.png)
 
same counts for all other processes - as if comment function is in general disabled..

**Comment by mkind** [comment]
commenting works for me in firefox and chrome at stage and dev :thinking:

**Comment by gereonrahnfeld** [comment]
works well after re-freshing - sorry for the short upheaval. Will close the issue.
