### ISSUE TITLE
Accordion elements look broken on opin-stage

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#1096]
Now that we can use accordions in the info descriptions, the design looks very broken. The font size of the title is too large (larger than the info tab headline) and the open/close icon is ugly (because it is not an icon but just a „+“ and an „x“ and not vertically centered.

https://opin-stage.liqd.net/de/projects/wie-sicher-fuhlst-du-dich-auf-dem-weg-zur-schule/#information

<img width="1053" alt="bildschirmfoto 2018-02-13 um 11 47 55" src="https://user-images.githubusercontent.com/15341015/36146127-e643d8a4-10b3-11e8-93d3-8c954431146f.png">

**Comment by MagdaN** [comment]
They are the same as on the FAQ Page and always looked like that: https://opin.me/de/help/faq/

**Comment by rittermo** [comment]
I know and they always looked bad to me. Since they are now used on the participation pages (and potentially on every project) they look much more out of place.
