### ISSUE TITLE
dashboard styling: width 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1116]
The left margin should be a little bit further to the left side (same height than OPIN logo), same counts for the right side.

![the left margin should be a little bit further to the left side_same height of opin_same counts for the right side](https://user-images.githubusercontent.com/15954895/36833906-41944f5c-1d31-11e8-8704-d1c092ba27db.png)

**Comment by phillimorland** [comment]
fixed, just tab padding make it look a little off but everything is aligned
