### ISSUE TITLE
dashboard styling: navigation box

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1117]
The difference between the title of the navigation boxes and its subcategories is not very sharp -  the way it is done at meinberlin would be better.
also: it would be great to have the exclamation mark in yellow
also: the hovering effect is almost invisible. Could we intensify it?

![difference between title and subcategories is not very sharp - perhaps the meinberlin way would be better _it would be great to have the exclamation mark in yellow](https://user-images.githubusercontent.com/15954895/36834046-d132fe4c-1d31-11e8-8f52-46cffc5f13de.png)

![screen shot 2018-02-28 at 17 36 34](https://user-images.githubusercontent.com/15954895/36834049-d4598b40-1d31-11e8-88da-f71fa13cd568.png)

**Comment by phillimorland** [comment]
quick draft dealing with issues mentioned, what do you think? @gereonrahnfeld let me know what needs changing! 
![opin me](https://user-images.githubusercontent.com/5871230/41983762-4b51e74c-7a2f-11e8-85e4-9a5061cd5e71.png)

**Comment by gereonrahnfeld** [comment]
@phillimorland I like the yellow exclamation mark as well as the hovering effect (although we don't need an underline, I think). With regard to the heading being more distinguished I am not sure - doesn't look that convincing to me but I don't have a better alternative. I think it would be great to ask @szukowski if she has already a design for this (or what her opinion would be. 

But anyways, thanks so much for working on the design.
