### ISSUE TITLE
dashboard: view and edit button link to the same content

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1118]
The view button in the project overview links to the same content the edit button links to (which is the project edit interface). It should link to the process.
Also: sometimes it is called view, sometimes preview. Is there a specific logic behind it or could we change this always to view?!

![view in project overview links to edit and not to the process_sometimes it is called preview sometimes view](https://user-images.githubusercontent.com/15954895/36834212-6f544b3a-1d32-11e8-815d-82ee3af87f8c.png)

**Comment by fuzzylogic2000** [comment]
will be fixed by #1115 

The logic behind view/preview is that one is already published and the other one isn't! I find it less confusing with that distinction.
