### ISSUE TITLE
dashboard: button remains grayed out

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1119]
When I press a button (e.g.) view and then go back to the interface where the button is, the button is greyed out. 

![whenever i press a button and then go back the button is greyed](https://user-images.githubusercontent.com/15954895/36838174-bde73f58-1d3e-11e8-866f-3db0a529df91.png)

**Comment by MagdaN** [comment]
@gereonrahnfeld I can not reproduce this, could you give some more details?

**Comment by gereonrahnfeld** [comment]
It happens when I click on view (for example). When I go back from the new page using the back arrow the button I clicked before is greyed out. Does that help?
