### ISSUE TITLE
Dashboard: information tab & result tab

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1123]
I would like to change the wording of information to information tab as well as of result to result tab in order to make it more understandable. Same counts for the wording when one enters this section: Instead of 'Edit project result' it should be 'Edit project result tab'. Same counts for information.

![i would like to change information to information tab_same counts for result as well as the both words in the headline](https://user-images.githubusercontent.com/15954895/36838816-803a7524-1d40-11e8-994f-239de01e3311.png)

**Comment by MagdaN** [comment]
@gereonrahnfeld these texts are defined in A4. If it is ok to all of you we can change it there, but it would then effect all the other projects

**Comment by gereonrahnfeld** [comment]
@rittermo : what do you say? I would like it very much. Perhaps you should speak about it in the product vision with Sandy first?

**Comment by rmader** [comment]
This can be done in the translation files, too, to keep it limited to the project
