### ISSUE TITLE
Dashboard styling: avatar picture should not have white background

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1124]
The avatar picture in the account settings has a white background colour. Please change this so it looks similar to the one next to the arrow in the top right section.

![avatar picture should not have white background](https://user-images.githubusercontent.com/15954895/36838920-c7484b4e-1d40-11e8-8e6b-3e742336ad2e.png)

**Comment by fuzzylogic2000** [comment]
fixed by #1158
