### ISSUE TITLE
Dashboard styling: height of organisation name in project list

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1125]
The organisation name in the project list is not on the same heights than the project and organisation tab. I would like to have this changed - similar to meinBerlin.

also: the height of projects and organisation moves depending on which tab I choose. Could we have it always on the same height - similar to meinBerlin.

![organisation name above project and organisation the latter not on the same height as well](https://user-images.githubusercontent.com/15954895/36839067-33abbfc8-1d41-11e8-9c59-dd68c07b0cd8.png)

**Comment by fuzzylogic2000** [comment]
fixed by #1158
