### ISSUE TITLE
dashboard: rename user in moderator section

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1126]
In order to make it more understandable I would like to change the text 'user' in the moderator section to 'Add user to list of moderators

also: could we replace the remove boxes with the same illustration we have for the participants? 

![the text user should be renamed to add user as moderator_also change edit with remove](https://user-images.githubusercontent.com/15954895/36839216-b1a678aa-1d41-11e8-898a-ed84c83aa644.png)

**Comment by MagdaN** [comment]
@gereonrahnfeld I would rather rename it to 'user search' or 'Search for user' something similar, as 'Moderators' is already written there two times, ok?

**Comment by MagdaN** [comment]
@gereonrahnfeld I changed like that, do you like it better? 

![bildschirmfoto 2018-03-19 um 17 45 28](https://user-images.githubusercontent.com/2905743/37609430-61b0f108-2b9d-11e8-9d02-98b806803c68.png)

**Comment by gereonrahnfeld** [comment]
perfect, thanks a lot. I'll close the issue.
