### ISSUE TITLE
Dashboard styling: spacing between texts and boxes

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1127]
Please add some space between the texts and the boxes in the dashboard. This not only counts for 'edit basic settings' but for each section. 

Also: the subtitles are smaller than the text below it - it should be at least the same size.

For more info on how much spacing we need and what size the text needs double-check with Sandy.

![subtitles are smaller than text below it - should be changed](https://user-images.githubusercontent.com/15954895/36839336-22084600-1d42-11e8-9228-08af31d2caf5.png)

![spacing_please extent the space between text and boxes](https://user-images.githubusercontent.com/15954895/36839420-540ea554-1d42-11e8-9799-3cccbfd0d439.png)

**Comment by phillimorland** [comment]
fixed
