### ISSUE TITLE
Dashboard styling: spacing between different sections

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1129]
When going to organisation details the headline is too close to the blue space. 
Also: the spacing between the different sections (i.e. title, header image, logo, twitter handle, facebook etc.) should always be the same. 
Also: they should be a little bit bigger than it is now (e.g. between Title and Header Image)
Also: please change Organisagtion to organisation

Concerning the spacing please double-check with Sandy.

![organisation without g_abstande sind unregelmassig - generell regelmassig und ein wenig grosser_abstand oberhalb der uberschrift grosser](https://user-images.githubusercontent.com/15954895/36839787-4f4834bc-1d43-11e8-9fa6-049fa2e1f423.png)

**Comment by MagdaN** [comment]
The Title and the spacing are the same as on all the other dashboard pages, therefore I would not change it

**Comment by gereonrahnfeld** [comment]
I see and think we might redo it in the future as part of a more general restyling story. 
Could close the story but won't because of the title change?

**Comment by MagdaN** [comment]
@gereonrahnfeld yes, I will close this for now, but when thinking of restyling we should keep in mind that it might effect all forms in opin e.g. when adding or editing an idea, and not just the ones in the dashboard

**Comment by gereonrahnfeld** [comment]
alright, thanks for mentioning it.
