### ISSUE TITLE
Dashboard styling: spacing between several subtitles, texts and save-button

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1130]
The spacing between the subtitles, texts and the buttons (especially the save button) is too little - especially in the 'edit basic information' section. Please add more space. 

Double-check with Sandy for this. 

![more spacing here](https://user-images.githubusercontent.com/15954895/36839947-b92b4a9a-1d43-11e8-98d3-d5f60194d7c0.png)

**Comment by fuzzylogic2000** [comment]
fixed by #1158
