### ISSUE TITLE
dashboard styling: the process images are not centred anymore

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1131]
In the area where I choose a process type the process images on the tiles are not centred anymore.

![screen shot 2018-03-01 at 11 32 00](https://user-images.githubusercontent.com/15954895/36840240-92c6bcbc-1d44-11e8-8d29-64c4913de89c.png)

**Comment by MagdaN** [comment]
@gereonrahnfeld I cannot reproduce this, which browser are you using?

**Comment by gereonrahnfeld** [comment]
@MagdaN weird, it does not exist anymore. Will close the issue..
