### ISSUE TITLE
Dashboard: member cannot be invited as moderator

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1132]
It doesn't work in the following case where ggr+99 is a member but cannot be invited as a moderator. 

![screen shot 2018-03-01 at 11 39 19](https://user-images.githubusercontent.com/15954895/36840452-555247b0-1d45-11e8-880a-56e38dd68b46.png)

**Comment by fuzzylogic2000** [comment]
@hello-kathi Is this still the case? And if yes, is it important?
