### ISSUE TITLE
Basic information tab not needed in OPIN dashboard

### ISSUE THREAD

**Issue by SabineJulia** [liqd/a4-opin#1144]
The basic information tab in the participation section doesn't appear in the project view. It should be taken out, if possible. 
![grafik](https://user-images.githubusercontent.com/24652917/37351040-7aa575de-26da-11e8-98e8-bc83edb49364.png)

**Comment by SabineJulia** [comment]
@gereonrahnfeld do you agree?

**Comment by gereonrahnfeld** [comment]
I have agree. Basic information is partly shown. 

Title of the module is shown above as the title (now: Participation) - the question is: is this necessary or would it rather be nice to always have as a module title sth like 'Module: Brainstorming' (etc.)

Short description of the module is not shown. 

@szukowski : could you please have a look at this and take it into consideration when doing the styling?

**Comment by MagdaN** [comment]
@kleingeist @CarolingerSeilchenspringer what do you think?

**Comment by kleingeist** [comment]
@gereonrahnfeld  @MagdaN  in meinBerlin the module title and description are used if there are multiple modules or offline events and thus have to be user editable:  see for example https://meinberlin-dev.liqd.net/projects/luwekn/
not sure what is shown in opins timeline if not the module title?

**Comment by gereonrahnfeld** [comment]
I kind of agreed with @szukowski  that it would be great to have in the first part, which describes the project, the following headline: "Project: <projectname>" and then in the second, third and so on (which describe the module) this headline: "Module: <modulename1>" , "Module: <modulename2>" etc. Also in meinBerlin this is a bit unclear now. If we change this we would increase the possibility for initiators to orient themselves.

**Comment by kleingeist** [comment]
ah sorry i thought you wanted to get rid of it altogether. im think it would be great to add the 'Project:/Module:' prefixes :+1:

**Comment by gereonrahnfeld** [comment]
cool, to make it more clear and because I forgot the project name and module names:

"Project: projectname"
"Module: modulename1"
"Module: modulename2"
etc.

**Comment by MagdaN** [comment]
@gereonrahnfeld as far as I understand @SabineJulia wants to get rid of the Basic Information Tab of the module, wording changes are part of these issues:

https://github.com/liqd/a4-opin/issues/1123
https://github.com/liqd/a4-opin/issues/1128 (which is closed, as I implemented it in OPIN)

**Comment by gereonrahnfeld** [comment]
that's true - I was referring to what @kleingeist said/asked. So as I understand it we should not get rid of the basic information because we also might want to edit the module title which will, in the future, be probably shown in the headline. 

I think if the short description that can be edited in the basic information is not shown anywhere we could get rid of it. @kleingeist do you use this information (short description) somewhere in meinBerlin?

**Comment by kleingeist** [comment]
yes both are used in meinBerlin (see attached image) altough i'am not sure if the meinBerlin timeline is really good.
Note, that it would also be possible to remove the basic information block from opins dashboard with little effort. 

![multi-module](https://user-images.githubusercontent.com/167407/37705028-f2ce551e-2cfa-11e8-9de6-5afd29ae9fe3.png)

**Comment by gereonrahnfeld** [comment]
alright, thanks for your remarks. 
I would leave it like it is at the moment and make its modification part of the session, when we discuss and take into consideratino Sandy's feedback (which is to a certain extend also concerned with this issue).
