### ISSUE TITLE
styling issue when attachment to an offline event should be deleted

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1151]
@szukowski : could you please have a look - looks broken. 

![screen shot 2018-03-15 at 16 14 03](https://user-images.githubusercontent.com/15954895/37472838-4c3a8858-286d-11e8-926d-b0e7622cc0b1.png)

**Comment by phillimorland** [comment]
more broken now
![screenshot_mod](https://user-images.githubusercontent.com/5871230/156538843-c0e3e790-dcd2-48b1-99c0-c988d6733209.png)

**Comment by hello-kathi** [comment]
@phillimorland still broken, can't be deleted
