### ISSUE TITLE
chharacters in username in user profile are cut off

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#1160]
Some characters of the user name might be cut off. Should the projects be as wide?

![screenshot from 2018-03-20 10-40-00](https://user-images.githubusercontent.com/8178179/37646945-51eb791c-2c2b-11e8-84fd-ac35f8096a72.png)

**Comment by gereonrahnfeld** [comment]
they don't have to be as wide, @szukowski : any design input concerning this issue?
If possible the characters shouldn't be cut off.

**Comment by fuzzylogic2000** [comment]
I guess they are as wide in the old design, because in most cases there will be only one project and with the normal tiles that wouldn't look to good. I will rename the issue as design-changes are no issues, but cut-off characters are. :)
