### ISSUE TITLE
although a project has already started I get the notification that it hasn't 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1165]
![screen shot 2018-03-21 at 17 44 39](https://user-images.githubusercontent.com/15954895/37723832-9f85722c-2d2f-11e8-9ecc-19ee59c6351e.png)

**Comment by fuzzylogic2000** [comment]
@hello-kathi or @sabinammm Could you check if this is still a problem? And when exactly. Is it a timezone-thing?

**Comment by sabinammm** [comment]
@fuzzylogic2000 @hello-kathi I tested this with timing going from not-started to started at the exact minute. It's working fine now, so I will close :)
