### ISSUE TITLE
Multi-loading of root document

### ISSUE THREAD

**Issue by rmader** [liqd/a4-opin#1175]
On opin-dev, there's an issue that the root document is loaded two times.
Turns out there's a project without an image, creating the following line:
`<img src="" class="project-tile-org-avatar" height="30" width="30" />`

The empty source is then interpreted as root document, e.g. "/en/"

As the root document takes the longest to load and creates the highest server load, we should try to solve that differently or make sure projects always have images (dummy images?)

**Edit:** hm, opin-stage also has empty images with empty source but the the browsers don't try to load it. I checked whether this has to do with the new security headers, but turning them off again didn't change the behaviour :/

**Edit2:** https://stackoverflow.com/questions/5775469/whats-the-valid-way-to-include-an-image-with-no-src

**Comment by treba123** [comment]
Hm still didn't find out what's different between opin-dev and opin-stage that this bug only affects dev, but here's another link that points out what happens:
https://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/

I think we should solve this before the next release as it slows down landing page speed quite a bit

**Comment by treba123** [comment]
Alright, we fixed it by setting the header image, which is loaded via css. If it's not set, it defaults to url(), which in turn defaults to "/". We should make sure we don't have this behaviour in other places, too.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 ok in the comments peps said it is fixed... do you know something about this? If not we can close

**Comment by fuzzylogic2000** [comment]
made issues in other projects to check we are fine there!
