### ISSUE TITLE
Usability: rating result looks clickable

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-opin#1190]
![screenshot from 2018-04-17 17-00-08](https://user-images.githubusercontent.com/2066372/38878860-3d912cd0-4262-11e8-9d11-b56450bc78b7.png)

One possible solution:
Make the whole element clickable and with a different (subtle) background color on mouseover

**Comment by fuzzylogic2000** [comment]
Yes! Also annoys me every time!
Do you think it should be clicakble, even if the description of the idea was not read before rating?

**Comment by ihucos** [comment]
>  Do you think it should be clicakble, even if the description of the idea was not read before rating?

Sorry, just read it now. Not sure. I'd say no.

**Comment by phillimorland** [comment]
How about making it clickable through to the idea? they can then easily leave a rating if that was their intention and they have to at least briefly look at the idea.

**Comment by fuzzylogic2000** [comment]
You mean linking it to the idea? So, if the rating in the list is clicked, the idea detail page is openend. I am not sure about that. 
Maybe it's more a design-thing at should look more it's showing a result and less like a button?
What do you think, @gereonrahnfeld or @SabineJulia ?

**Comment by phillimorland** [comment]
We can also try it like we have in meinberlin, the numbers and arrows being the same colour stops the arrows from being highlighted so I think it doesn't look as inviting to click

![opin2](https://user-images.githubusercontent.com/5871230/42030502-4b30b6ae-7ad3-11e8-8098-0add261cf56a.png)

**Comment by gereonrahnfeld** [comment]
But on meinBerlin it is the same than in OPIN isn't it?:
https://meinberlin-dev.liqd.net/projects/laermorte/?mode=list

![screen shot 2018-06-28 at 16 36 34](https://user-images.githubusercontent.com/15954895/42041123-83f24f7a-7af1-11e8-84ec-13c160e594e1.png)

**Comment by phillimorland** [comment]
No, Opin is currently like the top image where the numbers are black so arrows look highlighted.

**Comment by gereonrahnfeld** [comment]
I agree. But on meinberlin-dev the numbers are highlighted as well. This is why I am asking..

**Comment by fuzzylogic2000** [comment]
@ggr On meinberlin the arrows and numbers have the same colours, while on Opin the numbers are black and the arrows are coloured and by that look somehow actionable. I like @phillimorland idea to make both the same colour! What do you say, @SabineJulia ?

**Comment by gereonrahnfeld** [comment]
ah now I see what you mean. Sorry, I thought it was meant differently. ok from my side. @SabineJulia what do you think?

**Comment by SabineJulia** [comment]
yes I think it would be a good idea to make the arrows and numbers the same colour, I agree that it doesn't look as actionable.
