### ISSUE TITLE
Call to action extends into progress display in dashboard

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1194]
Using specific languages the call to action in the section offline events extends into the display of progress within the dashboard. 
This should be changed as follows. 
Call to action should always be aligned on the right side (and thus aligned on the progess display). 
If it then extends into the title of the section please move title of the section a bit lower. 
Call to action should always be at the same spot. 

![call to action dashboard](https://user-images.githubusercontent.com/15954895/38931460-81a7709e-4313-11e8-8604-358d2704094e.png)

**Comment by MagdaN** [comment]
I think this is a general problem with translated strings that get too long - we should add some general rules to the design on how to deal with long string and should try to avoid long - or at least much longer strings than in english - strings during translation.

**Comment by gereonrahnfeld** [comment]
I agree. @szukowski perhaps you could start this process (we shortly spoke about it already)

**Comment by phillimorland** [comment]
fixed with stacking
