### ISSUE TITLE
Cannot insert text in new paragraph in text review

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1201]
When I set up a new text review process and I add a new paragraph it is not possible for me to add text. 

![screen shot 2018-04-19 at 14 10 08](https://user-images.githubusercontent.com/15954895/38990789-e3a87f5e-43db-11e8-9d3c-ac377725f1d7.png)

**Comment by gereonrahnfeld** [comment]
It is firefox. The issue still exists. Could you please solve it before I test the text review export function? Cheeers.

**Comment by MagdaN** [comment]
could you maybe test in another browser, as this issue does not really belong to the userstory of exporting comments

**Comment by gereonrahnfeld** [comment]
Doesn't work in Safari and Chrome, either. I know that it does not belong to the US. However, it would make testing for me a lot easier. And has to be solved, anyways, due to it being crucial for the text review to be usable in general.
