### ISSUE TITLE
project overview in dashboard only displays up to 12 projects

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1203]
If one organisation has more than 12 projects they are not all displayed in the project overview of the dashboard. 
Might this be the same with beteiligung.in etc.?

See for example the organisation: Example for an organisation on opin.me (https://opin.me/en/orgs/opin-examples/) 

![screen shot 2018-04-19 at 15 45 51](https://user-images.githubusercontent.com/15954895/38995355-f97c7152-43e8-11e8-978f-a37e309f3969.png)

**Comment by rmader** [comment]
Apparently we miss pagination here - in a+ we have it

**Comment by fuzzylogic2000** [comment]
Hihi, yeah, sounds like we have pagination in django, but not in the html :scream_cat:

**Comment by fuzzylogic2000** [comment]
@sabinammm I found another issue for you!
To fix this, you have to 

1. find out, how we add the pagination to the project list in a+
2. see if we use a (styled) pagination elsewhere on opin and use its markup and style (or the include if there is one).

**Comment by sabinammm** [comment]
@fuzzylogic2000 yes: I found a pagination in opin, and used this. I think it might also be missing here: https://opin.me/en/orgs/opin-examples/?is_archived=all

**Comment by sabinammm** [comment]
@fuzzylogic2000 I rechecked again, and since there's no limit to the projects shown there, it's actually fine on https://opin.me/en/orgs/opin-examples/?is_archived=all.
