### ISSUE TITLE
find fix for hotfix in release3.1

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#1205]
CK editor is not loaded on all production systems when using it for document creation in a text commenting project, for release3.1 we added this hotfix https://github.com/liqd/a4-opin/commit/a30c2a87e45f119a6b44fa15d6e2e45f70a36a8f
based on the docs of django-ckeditor: https://github.com/django-ckeditor/django-ckeditor#installation

We should find a better fix!

**Comment by ihucos** [comment]
no idea whats going on there, but: use the "static" template tag instead? like in the upper lines
