### ISSUE TITLE
Offline events an more info of private projects visible even if not logged in

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#1209]
If I type in/ link to the URL of an offline event, I can see the event’s content and the info tab’s content of a private project.

For example, if you take this URL:
https://opin-stage.liqd.net/de/offlineevents/53/

you can access the information even if you are not logged in with an account.

**Comment by fuzzylogic2000** [comment]
But our private projects are a bit different than elsewhere. You can see them in the list for example and then request membership.
So, we want the project page to only display the membership request, then? I think, we should hide the offline events, but not the info about the project. You need the info to decide if you want to request membership, I would say. 
@hello-kathi what do you think?

**Comment by hello-kathi** [comment]
@fuzzylogic2000 That is difficult, but I think you are right. Hiding the offline event is important, because of safety and stuff. So not everyone can come to that offline event.

**Comment by fuzzylogic2000** [comment]
Currently, I can also see topics from the community module if I have the link. So, also check the ideas!

**Comment by Rineee** [comment]
Ideas can not be seen if the project is private. For the topics, adding the Permission Required Mixin solved it.
