### ISSUE TITLE
no call to action for react components when user is not logged-in

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1259]
When a user is not logged-in she doesn't see the polling. This should be changed to having a call to action similar to meinBerlin. 

![poll not displayed when not logged in](https://user-images.githubusercontent.com/15954895/41667331-fb9de912-74ac-11e8-8d43-231fe71d31f4.png)

**Comment by gereonrahnfeld** [comment]
@fuzzylogic2000 ah I see. How can we proceed from here? Would you reckon that this is a new US as well - or could it be fixed without translating it into one?

**Comment by fuzzylogic2000** [comment]
Yeah, as decided offline: we'll see how easy a fix it is.
