### ISSUE TITLE
Can't see complete text "Veröffentlichung rückgängig machen" in top right corner

### ISSUE THREAD

**Issue by PhilippMu** [liqd/a4-opin#1296]
![bildschirmfoto 2018-07-13 um 15 06 34](https://user-images.githubusercontent.com/41073836/42693193-9dcf3a66-86ae-11e8-9261-cf645115412a.png)

**Comment by phillimorland** [comment]
@hello-kathi is there any possibility of changing this wording to something like 'Unpublished' I can also add a break word!

**Comment by phillimorland** [comment]
fixed on chrom and ff
