### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [liqd/a4-opin#1349]
Hello @liqd

I noticed that your project doesn't have a logo.  I'd like to contribute to this warehouse. I have designed 2 different ideas representing the name of the project. What do you think about that? Also, we can create a logo by working together. I will wait for feedback. Have a nice day.

![a4](https://user-images.githubusercontent.com/36298335/46818148-2fbe1480-cd89-11e8-9d80-3c52fd7dd293.jpg)

**Comment by treba123** [comment]
Hej @reallinfo, sorry for the late reply and thank you for the offer, but actually the project already has a logo (you can find it on [opin.me](https://opin.me/en/)).
Still cool stuff, thank you for the input!
