### ISSUE TITLE
landing page: wrongly displayed

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1401]
Sometimes when I access OPIN.me the landing page is wrongly displayed. As soon as I reload the page it works fine again. This happens very often since a few weeks. @MagdaN @fuzzylogic2000 could you have a look what this could be about?

![screen shot 2019-01-07 at 17 33 59](https://user-images.githubusercontent.com/15954895/50780361-fff8ad00-12a2-11e9-9631-b08b4a1cfc29.png)

**Comment by fuzzylogic2000** [comment]
@ggr Could you check dev, if it's the same there? We just updated stuff, so I hope, this isn't the case anymore.

**Comment by gereonrahnfeld** [comment]
@fuzzylogic2000 I'll have a look. It only happens now and again. Very random. But I'll tell you in case I encounter this behaviour again.

**Comment by gereonrahnfeld** [comment]
@fuzzylogic2000 it happens again and again. It is really difficult to say why and when exactly. Pretty random from my point of view. Sometimes it even happens in Djano Admin. When I want to set up a new organisation for example only part of the information is shown..

![Screenshot 2019-04-04 at 14 37 11](https://user-images.githubusercontent.com/15954895/55557109-65650a00-56e9-11e9-95ee-c7c3392e35d9.png)

I think it would be good to take care of this, because there is an increasing number of organisations which want to use OPIN. (hurray)

**Comment by fuzzylogic2000** [comment]
@treba123 I have just seen your webpack/slick-carousel fixes in another project. Maybe sth. like that also solves this??

**Comment by rmader** [comment]
Closing for now, lets reopen if somebody can reproduce it.
