### ISSUE TITLE
Feedback Link on OPIN does not work anymore

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1497]
Could we just get rid of it? Or at least hide the link?

![Screenshot 2019-05-29 at 13 12 21](https://user-images.githubusercontent.com/15954895/58552768-7b87d600-8213-11e9-8600-5e6bbf95473c.png)

**Comment by hello-kathi** [comment]
Hi @fuzzylogic2000 @phillimorland @rmader it would be pretty cool if can do something here. Just delete it or hide it. Thank you :)
