### ISSUE TITLE
Adding moderators: some user names do not show up

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1505]
When I want to invite specific users as moderators it doesn't work. This counts for admin accounts (e.g. user name 'ggr'). And it also seems as if it is not the user names that is searched for but the email adress or rather the name of the email address before the '@' - sign.

**Comment by rittermo** [comment]
An initiator just called and he has the same problem. I quickly tested it and it does not seem to work with either usernames or email addresses. The web console gives me errors for the javascript.
![Bildschirmfoto 2019-06-25 um 12 01 19](https://user-images.githubusercontent.com/15341015/60089680-4e124780-9741-11e9-9ceb-b49e5cc6e818.png)

I will try adding the moderators via django admin, but we need to fix this at some point in the next sprint or two

**Comment by hello-kathi** [comment]
@MagdaN @fuzzylogic2000 would it be possible to solve this issue in the next two weeks or so? Could you please have a look and tell if it is easy to solve?

One Organisation needs this funktion and it doesn't work.
