### ISSUE TITLE
Changing the Organisation Details is not possible

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#1768]
**URL:** 
https://opin.me/en/dashboard/organisations/liquid-democracy/settings/
**user:** 
Initiators, who try to fill in the Organisations details & as an admin too.
**expected behaviour:** 
If I fill in Organisation details, save them and it is there
**behaviour:** 
I fill in the Organisation details, press save and it reloads, but do not save.
**important screensize:**

**device & browser:** 
Firefox 73.0.1 (64-Bit)
**Comment/Question:** 

Screenshot?

**Comment by rmader** [comment]
Hm, it's actually even better: there are a couple of fields that are required, so when creating an organisation and adding initiators one *has* to set them initially.

**Comment by phillimorland** [comment]
sorry I forgot to take my assignment off ages ago, are you on this now @rmader ?

**Comment by fuzzylogic2000** [comment]
Ah, so it worked before the dashboard, I guess? I suspected the language field thing update. Should I look into fixing this tomorrow or will you do today @rmader ?

**Comment by rmader** [comment]
It must have something to do with the translatable entries - in the dashboard there's only one while in the dashboard there are tabs at the top for every language. So yes, please continue :)

**Comment by rmader** [comment]
FWIW: apparently most organisations now have their info set in the english variant, no matter what language they actually use. So it might be easier to ditch the django-parler stuff - or fix it somehow :)
