### ISSUE TITLE
Link to organisation page in dashboard

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-opin#1801]
**URL:** any dashboard page
**expected behaviour:** that there is a link in the dashboard to the organisation home page
**behaviour:** we could use the name of the organistaion to link to home page as already has hover behaviour or we add a view button on org settings page like we do with projects
**Comment/Question:** frustrating when updating a project to not be able to click and see the updates

**Comment by rmader** [comment]
The same applies to a+-dev since the header redesign - no direct link. Should we get a design for that and then apply it here, too?

> we could use the name of the organistaion to link to home page

Na, like in a+ it's a dropdown if you are a member of several organisations.

**Comment by phillimorland** [comment]
@rmader in a+ we use the logo image next to the dropdown, @hello-kathi @mcastro-lqd would that be ok to do here, or would something else be preferable?

**Comment by mcastro-lqd** [comment]
The quickest solution would the link be on the name of the organization as you mentioned, but it would be nicer to show the organizations that the user is taking part/following and the ones owned by them below their avatar picture. Does that make sense? I can also provide you a mockup.

**Comment by phillimorland** [comment]
@mcastro-lqd a mock up would be cool if you aren't too stretched for time. I was thinking of putting the link on the logo (circled) and the organisation name is a dropdown when a person is an initiator in multiple organisations (the little chevron) sorry for my shit paint skills!
![Projekte — Test Organisation Dashboard — Homepage Opin me](https://user-images.githubusercontent.com/5871230/80499917-d539d880-896d-11ea-8b99-09372ec434df.png)

**Comment by mcastro-lqd** [comment]
@phillimorland ah sorry, I thought that it was related to other sreen, that also looks good! Thanks!
