### ISSUE TITLE
comments can't be edited

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#1844]
**URL:** https://opin-dev.liqd.net/en/maps/erster-vorschlag/
**user:** any user
**expected behaviour:** 
**behaviour:** The whole react component disappears, when the edit-button is clicked
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Dev-Tools:
`TypeError: "can't convert undefined to object"`

**Comment by fuzzylogic2000** [comment]
@Rineee As it was already merged, this became an issue. :)

**Comment by fuzzylogic2000** [comment]
:) https://github.com/liqd/adhocracy4/issues/527

**Comment by Rineee** [comment]
> @Rineee As it was already merged, this became an issue. :)

Alright! I am still a bit hesitant with writing issues bc of lack of overview.. but I will try to be more brave in the future!

**Comment by fuzzylogic2000** [comment]
@Rineee You can whack everything in an issue, we can easily discuss and/or simply close again!
