### ISSUE TITLE
Timeline is broken in project view

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#1847]
**URL:**https://opin-dev.liqd.net/en/projects/test-bootstrap/
**user:** *moderator/ initiator/ participants/ visitors (non-logged-in)/ admin/ cms-editors/ developers*
**expected behaviour:** *The time is a line which you can see offline events and other points in a row*
**behaviour:** *Time doesn't show offline events and broke into more paragraphs*
**important screensize:** *mobile? desktop?*
**device & browser:** * firefox 74 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?* 

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

<img width="519" alt="Bildschirmfoto 2020-04-28 um 09 23 08" src="https://user-images.githubusercontent.com/52459078/80459139-3348ca80-8932-11ea-87b3-4912c35718ff.png">
<img width="588" alt="Bildschirmfoto 2020-04-28 um 09 21 58" src="https://user-images.githubusercontent.com/52459078/80459144-33e16100-8932-11ea-92b5-4a99b974226e.png">

**Comment by phillimorland** [comment]
this was fixed with bootstrap issues
