### ISSUE TITLE
missing migration for timezone

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#1850]
probably due to some update?

**Comment by rmader** [comment]
Fixed by https://github.com/liqd/a4-opin/pull/1852 - maybe we should re-evaluate if it's a good idea to use timezones in models :)

**Comment by fuzzylogic2000** [comment]
Krr, I guess it's as good an idea as to use languages... Both make these things settable for the user, but can cause these unexpected migrations. I can't think of another way to do it. Can you @rmader ?
