### ISSUE TITLE
#2832[OPIN] Update Bootstrap and font awesome UX/UI Test

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-opin#1857]
**URL:** https://opin-dev.liqd.net

**Comment/Question:**
 
<img width="371" alt="Screenshot 2020-04-28 at 14 28 57" src="https://user-images.githubusercontent.com/59610786/80509380-a164b000-8979-11ea-9f12-73c813a46b7d.png">
**1** – Is this height right? Cause it looks a bit off 

<img width="817" alt="Screenshot 2020-04-28 at 14 29 51" src="https://user-images.githubusercontent.com/59610786/80509451-b9d4ca80-8979-11ea-8db8-d2adc13271b1.png">
**2** – Is it possible to add here some spacing? Cause the "Verify..." title seems to close to the notification. 

<img width="935" alt="Screenshot 2020-04-28 at 14 42 20" src="https://user-images.githubusercontent.com/59610786/80509671-03bdb080-897a-11ea-9789-70ecc75e0eda.png">
<img width="370" alt="Screenshot 2020-04-28 at 17 53 18" src="https://user-images.githubusercontent.com/59610786/80510834-8dba4900-897b-11ea-96fa-a94ab9f3715c.png">
**3** – Mobile and Desktop -> Here it looks like the spacing between message and tags are super off. Is it possible to make it a bit more like on a+. If needed mockup, I can put it on Zeplin! :) 

<img width="496" alt="Screenshot 2020-04-28 at 14 42 30" src="https://user-images.githubusercontent.com/59610786/80509825-349de580-897a-11ea-8c5f-a9500a90c647.png">
<img width="363" alt="Screenshot 2020-04-28 at 17 53 07" src="https://user-images.githubusercontent.com/59610786/80510733-6b283000-897b-11ea-88dc-9f0cb0af7fbf.png">
**4** – The comments also seem a bit off (mobile and desktop). 

<img width="210" alt="Screenshot 2020-04-28 at 14 43 49" src="https://user-images.githubusercontent.com/59610786/80509996-6747de00-897a-11ea-954d-3ec7310d0f1e.png">
**5** – There is a bug here with these grey lines. 

<img width="579" alt="Screenshot 2020-04-28 at 14 50 40" src="https://user-images.githubusercontent.com/59610786/80510155-a2e2a800-897a-11ea-8c10-b62084e4fdd1.png">
**6** – Are the like/comment icons here right? Cause it looks a bit off as well. 

<img width="442" alt="Screenshot 2020-04-28 at 14 46 17" src="https://user-images.githubusercontent.com/59610786/80510305-d291b000-897a-11ea-8724-1eabff2214b5.png">
**7** – The burger menu icon doesn't seem to work on mobile for me. 

<img width="447" alt="Screenshot 2020-04-28 at 14 46 36" src="https://user-images.githubusercontent.com/59610786/80510502-1a183c00-897b-11ea-9f91-6952f3cb4a95.png">
**8** – The tiles width are a bit different here, it might be the same thing that happened with CE.

<img width="194" alt="Screenshot 2020-04-28 at 14 49 34" src="https://user-images.githubusercontent.com/59610786/80510630-49c74400-897b-11ea-8c0a-9077361f1b33.png">
**9** – Here, on mobile, the grey line also seem off. 

<img width="378" alt="Screenshot 2020-04-28 at 17 53 48" src="https://user-images.githubusercontent.com/59610786/80510875-9d399200-897b-11ea-948b-431196a43232.png">
**10** – Here this part is cutting on Mobile. 

![Screenshot_2020-04-28 Homepage Opin me](https://user-images.githubusercontent.com/59610786/80511196-13d68f80-897c-11ea-944b-6609adcf0c52.jpg)
**10** – If possible add spacing between the main banner and "Latest projects..." + Login button seems to be cut here too.

Thanks a lot!

**Comment by phillimorland** [comment]
@mcastro-lqd **3** – I would love a mockup please! :) we didn't apply any styling to the comments yet, it might be that we don't style them properly till the styling sprint but i'll try get them a little polished

**Comment by mcastro-lqd** [comment]
3 - here you go https://app.zeplin.io/project/5b051f6db0161ad12b6bbbba/dashboard?seid=5ea9b100d95bf3bb2ade6f40
