### ISSUE TITLE
Should the idea (and topic) image upload also have the same checkbox as in a+?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#1858]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** Images can be added by users without confirming they have the right to use them.
**important screensize:**
**device & browser:** 
**Comment/Question:** In a+, we make users tick a box saying that they have the right to use the image. Maybe that's also a good solution here?

**Comment by fuzzylogic2000** [comment]
@hello-kathi This question is for you, I would say. :)

**Comment by hello-kathi** [comment]
@fuzzylogic2000 it is! Let's do this!
