### ISSUE TITLE
idea and topic images are suuuuperbig

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#1860]
**URL:** idea: https://opin-dev.liqd.net/en/maps/na-gut/
topic: https://opin-dev.liqd.net/en/communitydebate/lalala-lets-talk-about-stuff/
**user:** 
**expected behaviour:** 
**behaviour:** The images for ideas and topics are suuuperbig. As these images are there to show something about the idea, but aren't the most important thing, they seem a bit too big and distracting. Also, the image to add as a user has to be very big to be allowed to upload.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
@mcastro-lqd do you have a preference or ideas about the size/layout of ideas and topics with images?

**Comment by mcastro-lqd** [comment]
@phillimorland Would it be possible to set a max height for cropping these images(like 200-240px) as a header image? 

Maybe we can change the text here as well to "Upload a header picture" or something. So it's clear that its possible to upload more pictures below.

<img width="750" alt="Screenshot 2020-05-19 at 14 49 41" src="https://user-images.githubusercontent.com/59610786/82328317-fc6d4e00-99df-11ea-9464-f3f3a3312125.png">

**Comment by phillimorland** [comment]
@mcastro-lqd I can set it to that, I'm not sure it would be called header image in that case though, maybe just idea image and it can be displayed next to idea? we can maybe have a quick chat about it?

**Comment by mcastro-lqd** [comment]
@phillimorland Yeah, "Idea image" might be good as well, shall we ask kathi?

**Comment by phillimorland** [comment]
@hello-kathi instead of a header image for ideas we were thinking we make it more like a+ and have an idea image and display it similar to attached, what do you think?
![This is an idea — adhocracy Teststadt](https://user-images.githubusercontent.com/5871230/82886479-db0fe300-9f46-11ea-8674-8cc40ce5af77.png)

**Comment by hello-kathi** [comment]
@phillimorland superb! Let's do this! Thank you
