### ISSUE TITLE
running the tests takes very very long

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#1890]
**URL:** 
**user:** 
**expected behaviour:** tests run in a reasonable time
**behaviour:** running the tests needs minutes, no matter if they are run with or without --reuse-db
**important screensize:**
**device & browser:** 
**Comment/Question:** As --reuse-db doesn't change anything, there must be some other setup that takes long?!

Screenshot?

**Comment by fuzzylogic2000** [comment]
times are:
```
make test
== 139 passed, 83 warnings in 249.19s (0:04:09) ==

make test-clean
== 139 passed, 83 warnings in 249.21s (0:04:09) ==

# only one test (clean db) - 
py.test tests/ideas/test_idea_views.py 
== 7 passed, 7 warnings in 231.74s (0:03:51) ==

# only one test (reuse db) - 
py.test tests/ideas/test_idea_views.py --reuse-db
== 7 passed, 7 warnings in 237.88s (0:03:57) ==
```
As the number of tests and the fresh or old testing DB don't make a difference, there must be something else in the setup. Images?

**Comment by fuzzylogic2000** [comment]
fixed itself.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 beste fix! <3
