### ISSUE TITLE
#2829 [OPIN] Community Modul for OPIN – #2846 UX/UI testing 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-opin#1891]
**URL:** https://opin-dev.liqd.net/en/projects/community-debatte/

**Comment/Question:** 

Hi, there are still a couple of things a bit off: 

**01** – The avatar is still a bit far from the name and date. (not urgent, just mentioning) 
<img width="254" alt="Screenshot 2020-05-12 at 16 58 29" src="https://user-images.githubusercontent.com/59610786/81711169-a34b6a80-9473-11ea-9feb-75bca1a182cd.png">
 
 
 **02** – The share dialog box is a bit off as well, it's missing some padding at the bottom part and once the button turns green(copied), it gets bigger than the input field. 
<img width="963" alt="Screenshot 2020-05-12 at 16 58 48" src="https://user-images.githubusercontent.com/59610786/81711250-bcecb200-9473-11ea-93b8-d86fbd980cfb.png">
 
 
 **03** – Tags here are still touching the comment box and the cancel button looks a bit smaller than the save changes one, is that supposed to be like that? 
<img width="938" alt="Screenshot 2020-05-12 at 16 59 05" src="https://user-images.githubusercontent.com/59610786/81712047-806d8600-9474-11ea-9a96-cea41b0fc87f.png">
 
 
 **04** – On mobile, the share button seems that it could fit on top, don't you think? Since we have no Report here, it might look better. 
<img width="402" alt="Screenshot 2020-05-12 at 17 08 24" src="https://user-images.githubusercontent.com/59610786/81712237-aa26ad00-9474-11ea-8c9a-8dfa075a9ee5.png">

 
 **05** – Same as 03 but on Mobile. 
<img width="423" alt="Screenshot 2020-05-12 at 17 08 46" src="https://user-images.githubusercontent.com/59610786/81712598-143f5200-9475-11ea-8deb-28cccb331bc5.png">
 
 
 **06** – On Mobile, the notification seems not centered + white spacing above. 
<img width="449" alt="Screenshot 2020-05-12 at 17 09 28" src="https://user-images.githubusercontent.com/59610786/81712628-1e615080-9475-11ea-8294-c6817b329942.png">
 
 

Let me know if something is unclear! Thanks a lot again :)

**Comment by phillimorland** [comment]
@mcastro-lqd 6 - I cannot replicate, what browser, size were you viewing on?
