### ISSUE TITLE
Initiators gets Error 403 when deleting Offline Events

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#1940]
**URL:https://opin.me/de/dashboard/offlineevents/offline-test/delete/
https://opin.me/de/projects/magda-testet-brainstorming/** 
**user: Initiator** 
**expected behaviour: As an Initiator I want to delete an Offline Event and then it is deleted** 
**behaviour:As an Initiator I get an Error 403 if I click on delete in the Project dashboard** 
**important screensize:**
**device & browser: Firefox, Chrome, Safarie** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@hello-kathi We were meant to fix this one before the release, right? I added a milestone. Could you please check the other issues and assign them with this milestone if they need to be fixed prior to the release? Thank you!
