### ISSUE TITLE
Styling (line & text) in Participate is weird

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#1956]
**URL:** https://opin-stage.liqd.net/de/projects/
**user:** participant
**expected behaviour:** If I click on participate sehr are to options: find projects or find organisation. The Spacing is to close and the loine is to close
**behaviour:** I put a screenshot from Stage and a screenshot from productive into this issue. It is easier to show tat way
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1137" alt="Bildschirmfoto 2020-07-27 um 11 14 08" src="https://user-images.githubusercontent.com/52459078/88525433-dfb24f80-cffa-11ea-8979-3d3519a41cd0.png">
<img width="1205" alt="Bildschirmfoto 2020-07-27 um 11 12 57" src="https://user-images.githubusercontent.com/52459078/88525440-e17c1300-cffa-11ea-9db2-9339326d8355.png">

**Comment by phillimorland** [comment]
duplicate issue
