### ISSUE TITLE
Modul Tiles

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#1958]
**URL:** https://opin-stage.liqd.net/de/dashboard/organisations/liquid-democracy-ev/blueprints/
**user:** Initiator
**expected behaviour:** two tiles + dht
**behaviour:** dht+ one tile it is not that bad, but it feels kind of empty
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1117" alt="Bildschirmfoto 2020-07-27 um 11 28 20" src="https://user-images.githubusercontent.com/52459078/88526631-759aaa00-cffc-11ea-94ae-0e44a3237d08.png">
<img width="1160" alt="Bildschirmfoto 2020-07-27 um 11 28 14" src="https://user-images.githubusercontent.com/52459078/88526637-77646d80-cffc-11ea-93e9-51f9cd22aa3a.png">

**Comment by fuzzylogic2000** [comment]
Where is the second screenshot from? prod? Looks like the fontsize is bigger on the first screenshot?!

**Comment by hello-kathi** [comment]
@fuzzylogic2000 yes the second one is from prod. One is bigger and is smaller,  I think.

**Comment by fuzzylogic2000** [comment]
* was version v3.8 on prod, v3.9 on stage!

**Comment by Rineee** [comment]
This seems fixed already, otherwise please open again @hello-kathi
