### ISSUE TITLE
Delete Button in Community Modul/offline Event File Upload is to far away from the word delete

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#1960]
**URL:** https://opin-stage.liqd.net/de/dashboard/offlineevents/title-party/update/
**user:** *initiator*
**expected behaviour:** *If I want to delete an Upload, the check box should be near to the word*
**behaviour:** *It seems far away and brolken, but it works!*
**important screensize:** *desktop?*
**device & browser:** *e.g. Desktop, firefox 74.4 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?* 

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.
<img width="1280" alt="Bildschirmfoto 2020-07-27 um 11 42 18" src="https://user-images.githubusercontent.com/52459078/88528214-99f78600-cffe-11ea-8a22-059874ed9f80.png">

**Comment by Rineee** [comment]
Also seems fixed already
