### ISSUE TITLE
language tabs in organisation form dont work properly 

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-opin#2028]
**URL:** 
**user:** 
**expected behaviour:*I can switch back and forth through tabs* 
**behaviour:*all tabs that have been clicked once stay active. This means that it is not possible to open a tab a second time bc it then doesnt get activated anymore (e.g switching to german tab, then to english tab and back to german will not work, but stay on english tab)* 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
fixes with ks-2020-10-fix-community-debate-upload-forms-error
