### ISSUE TITLE
Error 500 when trying to open "Start Project Page" in Wagtail

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2074]
**URL:** https://opin.me/de/start-your-project/
**user:** Admin
**expected behaviour:** If I am on the Page Start Project and click on wagtail icon and on edit this page, then I came to the wagtail editor for this page
**behaviour:** I get an error 500
**important screensize:**
**device & browser:** Mozilla
**Comment/Question:** 
That happens too, If I am trying to get to this page navigating in wagtail
Screenshot?

**Comment by fuzzylogic2000** [comment]
There are changes in draft from 2018. The updates inbetween might have broken it. There is no way to revert the page to an old revision.

@hello-kathi Sorry, that we couldn't help with that. Did you copy it over to a new one?

**Comment by hello-kathi** [comment]
@fuzzylogic2000 No worries! I have to check it, And will do a new page!

**Comment by fuzzylogic2000** [comment]
@hello-kathi Did you do a new page? Can we close this issue? We can't actually do anything about it...

**Comment by hello-kathi** [comment]
@fuzzylogic2000 yes,  I am on int because there are some pages like that :(
