### ISSUE TITLE
Three Coloumn Block is not right centered

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2075]
**URL:** https://opin-dev.liqd.net/en/
**user:** Admin
**expected behaviour:** all the 3 Coloumns should be centered the same
**behaviour:** It looks, like all blocks have different allignments
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1269" alt="Bildschirmfoto 2020-11-03 um 15 01 07" src="https://user-images.githubusercontent.com/52459078/97994279-70ac7a00-1de5-11eb-9072-23808522c45f.png">

**Comment by Rineee** [comment]
Also fixed already? If not, please reopen @hello-kathi
