### ISSUE TITLE
Show Preresults in Poll is broken

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2106]
**URL:https://opin-stage.liqd.net/de/projects/christmas/** 
**user:Initiator** 
**expected behaviour:If I set up a poll and publish it there is the Text: "Vorläufiges Ergebniss anzeigen" and I can click that and see results without voting** 
**behaviour:If I set up a poll there is the Text: "Vorläufiges Ergebnisse anzeigen" but it is not a Button or any field to do this,just the text. So I have to vote to see results or wait till the poll is over. But as Initiator I maybe don't want to vote, just see the PreResult.** 
**important screensize:**
**device & browser: Firefox82.0.2 (64-Bit), Safari Version 14.0 ** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
This will only be fixed by the a4-update, but that will be soon!
