### ISSUE TITLE
tabs on participate page have no padding

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#2164]
**URL:** https://opin.me/en/orgs/
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Screenshot from 2021-04-29 11-53-34](https://user-images.githubusercontent.com/8178179/116533487-b902ab80-a8e1-11eb-9d0b-1090b9d9a7da.png)

**Comment by phillimorland** [comment]
duplicate
