### ISSUE TITLE
Should not need to install popper

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-opin#2248]
Popper is installed in a4 for poll, we should not need to install it again in Opin

**Comment by phillimorland** [comment]
@khamui do you know why we don't need to install react-popper in mB but do here?

**Comment by khamui** [comment]
@phillimorland when i remember right, in meinBerlin popper.js (name of the previous version) was installed, but was removed because it was installed but not used. Instead `react-popper` was added to meinBerlin. hum...probably it should be installed in a4 instead...
