### ISSUE TITLE
organisation form broken

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-opin#2249]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** the form to add description etc in different languages is broken
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Form is broken since this commit https://github.com/liqd/a4-opin/commit/c4818ce91a1fac016223ea6d41a751a21b905059 , but going back to react 16.x does not help. Updating Aplus to react 17 also breaks the form there.

The page reloads on click of a language button (can be removed by adding preventDefault inside react_language_switch.activateTab) but the activation of  the corresponding tab content still does not work (stays on engl content.)

The onClick event is missing for the broken form, see screenshots.
![button_broken](https://user-images.githubusercontent.com/9589411/126141442-62eb702c-e85b-413f-98e4-77ad47272742.png)
![button_working](https://user-images.githubusercontent.com/9589411/126141454-4fd3cb8d-5940-40f4-a0cf-d16c75213389.png)

**Comment by phillimorland** [comment]
NOTE: this was attempt to fix it by building it like a+ https://github.com/liqd/a4-opin/pull/2237

**Comment by phillimorland** [comment]
@Rineee is there a pull request with how far you got? maybe you can push it and tag it here?

**Comment by Rineee** [comment]
@phillimorland no there is no pull request that did anything useful, sorry. I wrote up all I know above
