### ISSUE TITLE
#4410 Add new Poll Module - Voting

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-opin#2259]
**URL:** https://opin-dev.liqd.net/en/projects/testing-poll/
**important screensize:** *Both*
**device & browser:** *Safari Version 14.1.1*
**Comment/Question:** *Comments on pdf + some screenshots* 

Desktop:
[d-Poll-Voting.pdf](https://github.com/liqd/a4-opin/files/6856473/d-Poll-Voting.pdf)

Mobile:
[m-Poll-Voting.pdf](https://github.com/liqd/a4-opin/files/6856474/m-Poll-Voting.pdf)

On Mobile: When answers are saved, the green notification close button is off. 
<img width="357" alt="Screenshot 2021-07-21 at 15 11 00" src="https://user-images.githubusercontent.com/59610786/126504602-8414e944-9036-4976-a33c-3f4f72957648.png">

**Comment by phillimorland** [comment]
@mcastro-lqd this is becasue the answer is selected, was this not part of the design? (I know we wern't following the redesign for this story but I thought it should be kept?)

Note: button notification to be fixed in a4

**Comment by mcastro-lqd** [comment]
@phillimorland 01: ah ok, my bad then, I thought it was like meinBerlin here that only the checkmark fiel turns into blue. :)

Thanks
