### ISSUE TITLE
#4410 Add new Poll Module - Results

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-opin#2260]
**URL:** https://opin-dev.liqd.net/en/projects/testing-poll/
**important screensize:** *Both*
**device & browser:** *Safari Version 14.1.1*
**Comment/Question:** *Comments on pdf + some screenshots* 

Desktop:
[d-Poll-Results.pdf](https://github.com/liqd/a4-opin/files/6856552/d-Poll-Results.pdf)

Mobile: 
[m-Poll-Results.pdf](https://github.com/liqd/a4-opin/files/6856553/m-Poll-Results.pdf)

**Comment by phillimorland** [comment]
NOTE: 
arrows is a4 issue to be fixed there
Comment issues also a4 and not part of this story but part of BS update to be added in seperate issue
