### ISSUE TITLE
#4409 headline field is missing

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#2267]
**URL:** 
https://opin-dev.liqd.net/de/test-page-for-4409/
**user:** 
admin
**expected behaviour:** 
I should be able to add a headline for the CTA block.

**behaviour:** 
There is no field to add a headline for the CTA block

**important screensize:**
all sizes

**device & browser:** 
macOS 11.4., Safari 11.4.1
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
I read the acceptance criteria as the columns having a headline, should they not?

**Comment by rittermo** [comment]
@phillimorland The headline per column is there and fine. The headline for the block as a whole is missing.

**Comment by phillimorland** [comment]
@rittermo theres only 1 in the acceptance criteria?! we can add one or it can be added by using a single column block before a multi column but if we are following the AC it doesn't appear to be included

**Comment by rittermo** [comment]
@phillimorland I wasn’t in refinement (were you @mcastro-lqd ? ) and the AC for the headline is, unfortunately, ambiguous. The design in zeplin shows a general headline for the whole block and headlines/bold text for each column. If it is too time consuming to add a headline field, then it will have to wait for another user story.

**Comment by mcastro-lqd** [comment]
@phillimorland @rittermo From what I got from Kathi, they wanted the content structure really like the one on a+ so there should be a general headline + 3 columns with an icon + headline + body text each

**Comment by phillimorland** [comment]
@rittermo @mcastro-lqd neither of us were in the final refinement unfortunatly, theres been quite alot of guessing with this, i'll check how quick this will be if not I can add the general headline block from the other pages, it'll be quick and that way it can be added to any of the blocks incase it was also missed in the AC of other stories

**Comment by rittermo** [comment]
@phillimorland Thank you! That’s awesome and sorry for the ambiguity in the requirements!
