### ISSUE TITLE
account settings: Select list look like input fields

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#2290]
**URL:** 
https://opin-dev.liqd.net/en/accounts/profile/

**user:** 
logged-in participant

**expected behaviour:** 
Select lists should have an arrow or UI element to indicate that they can be clicked to make a select list appear and to differentiate them from input fields.

**behaviour:** 
The select lists look like text input fields.

**important screensize:**
all sizes

**device & browser:** 
macOS 11.4, Safari 11.4.1

**Comment/Question:** 

Screenshot?
<img width="998" alt="Bildschirmfoto 2021-08-02 um 17 47 28" src="https://user-images.githubusercontent.com/15341015/127889025-db584e75-886a-40db-9af9-ff036e58cdbf.png">

**Comment by fuzzylogic2000** [comment]
@hello-kathi Maybe we also need to fix this before release?
