### ISSUE TITLE
Underlined Links in User Drop down menu

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2304]
**URL:** https://opin-dev.liqd.net/de/
**user:** all
**expected behaviour:** The indivual items like Administartor, Account Settings, Organsaitions are clickable and linked to the sections but not unterlined. The font color change from black to blue if I am hovering over the links/text.
**behaviour:** The items are underlined
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="716" alt="right" src="https://user-images.githubusercontent.com/52459078/130023526-dc6c6941-dd32-42ee-8606-0125cf2310cd.png">
<img width="414" alt="wrong" src="https://user-images.githubusercontent.com/52459078/130023554-0f1b5a79-b495-47ab-ad58-807e0d8b293a.png">

**Comment by fuzzylogic2000** [comment]
Closed by #2311
