### ISSUE TITLE
remove dropdown underlines from links (and buttons) in menu

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#2316]
@fuzzylogic2000 ah thanks for looking. No we had the underlined links nowhere before, so it shouldn't be in any dropdown. I just checked the filters and there it is (already) gone.
But I found another one... I will write an new issue, sorry for missing that.
<img width="1268" alt="Bildschirmfoto 2021-08-30 um 12 08 12" src="https://user-images.githubusercontent.com/52459078/131323610-aebc3204-89a3-44b2-9b2d-77db96ce7e3e.png">

_Originally posted by @hello-kathi in https://github.com/liqd/a4-opin/issues/2311#issuecomment-908217289_

**Comment by fuzzylogic2000** [comment]
@khamui Sorry, I don't know where to look for the underlined dropdown. Maybe check what's in the image? Otherwise you could check if you can find any dropdown with underlines?

And @hello-kathi you can just use this issue and put into it when you find more underlined dropdowns (before we found and fixed them all).

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @khamui you already removed everything, right? Because I was looking for, checking my old screenshots, and it was gone :D
