### ISSUE TITLE
Spacing from the Video Block

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2428]
**URL:** https://opin.me/en/use-cases/how-to-conduct-a-consultation-for-youth-policy/
**user:** Admin
**expected behaviour:** When I use the video Block there is a bit of space between the last block and the videoblock
**behaviour:** There is no space
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1357" alt="Bildschirmfoto 2022-02-09 um 13 50 32" src="https://user-images.githubusercontent.com/52459078/153204818-39c3b7d9-96ec-407d-b632-cd9bb1ca8665.png">

**Comment by phillimorland** [comment]
@hello-kathi having trouble replicating this, I can only find the following block that can be seen but it doesn't look like your screen shot, can you replicate the issue on dev? https://opin-dev.liqd.net/en/manual-index-page/manuals-section-page/manual-detail-page
![screenshot(23)](https://user-images.githubusercontent.com/5871230/157689205-4d6f85f0-26ec-4b98-ac04-08f5605ea02e.png)
/

**Comment by hello-kathi** [comment]
@phillimorland 
https://opin-dev.liqd.net/de/best-practices/from-youth-horizont-in-georgia/

It is happening when you have a 1-2 Column Block in Colour and then the video Block.
With no background colour in te 1-2 Column Block it is fine.So I think it is the spacing between the "Colourframe and the next Block type, in this case the Video Block Headline.
<img width="1288" alt="Bildschirmfoto 2022-03-11 um 08 37 41" src="https://user-images.githubusercontent.com/52459078/157823327-399c6a7d-4fc3-49e5-b8d3-66eba27fa63d.png">

**Comment by phillimorland** [comment]
@hello-kathi is it ok now?

**Comment by hello-kathi** [comment]
@phillimorland yes! Thank you!
