### ISSUE TITLE
Image Text Block Image is very small

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2432]
**URL:** https://opin.me/en/our-opin-ambassadors/
**user:** Admin
**expected behaviour:** In this Block I would expect a bigger picture
**behaviour:** The Picture is very small
**important screensize:**
**device & browser:** 
**Comment/Question:** 
This block was never used, so maybe it was always like that. But with a bigger picture it would be very usefull
Screenshot?
<img width="1398" alt="Bildschirmfoto 2022-02-10 um 09 20 46" src="https://user-images.githubusercontent.com/52459078/153366605-351a3e75-18e2-4bbb-ae66-66268c1b6928.png">

**Comment by phillimorland** [comment]
@hello-kathi I can't find the example in the link here but I think the confusion comes from the naming of this block, in the code this is a ImageTextBlockList and is meant to look like the image below, Should this one still be altered?
![screenshot(24)](https://user-images.githubusercontent.com/5871230/157694425-78be1fdf-f9c3-47dc-8e95-dcb100ed8c21.png)

**Comment by hello-kathi** [comment]
@phillimorland no drop it like its hot.
