### ISSUE TITLE
Ambassadors Banners

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-opin#2434]
**URL:**https://opin-dev.liqd.net/en/opin-amabassadors/
**important screensize:** *Desktop*
**device & browser:** *Safari*
**Comment/Question:** *Text is off here* 
<img width="1562" alt="Screenshot 2022-02-16 at 11 29 38" src="https://user-images.githubusercontent.com/59610786/154246089-75f831d8-36eb-438f-b54e-00c7bea30ee7.png">

**Comment by hello-kathi** [comment]
I have to say here I just tried something. So I used the 1-2 highlighted column cta block and just used one column. So it is not used in the way it should be ;)

**Comment by phillimorland** [comment]
@hello-kathi I've altered it to use 2 cols, what do you think?

**Comment by hello-kathi** [comment]
@phillimorland yes I think so too! Perfect!
