### ISSUE TITLE
filter out deprecated timezones

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-opin#2439]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** We have a timezone field for the user to choose a timezone. Old deprecated timezones are included in the list (see link below).
**important screensize:**
**device & browser:** 
**Comment/Question:** https://adamj.eu/tech/2021/05/06/how-to-list-all-timezones-in-python/

Screenshot?

**Comment by sabinammm** [comment]
"common_timezones is a list of useful, current timezones. It doesn’t contain deprecated zones or historical zones, except for a few I’ve deemed in common usage, such as US/Eastern (open a bug report if you think other timezones are deserving of being included here). It is also a sequence of strings."

http://pytz.sourceforge.net/
