### ISSUE TITLE
In the Poll Blueprint we refer to the OPIN App

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2461]
**URL:** https://opin.me/en/dashboard/organisations/opin/blueprints/
**user:** All
**expected behaviour:** 
Run customizable, multi-step polls on OPIN to get detailed opinions on topics from the public or your members. 
Phase 1: Answer the questions and comment on the poll.

**behaviour:** 

Run customizable, multi-step polls on OPIN to get detailed opinions on topics from the public or your members. **Via the OPIN polling app for iOS and Android these polls are also accessible on smartphones.**
Phase 1: Answer the questions and comment on the poll.

**important screensize:**
**device & browser:** 
**Comment/Question:** 
I already changed the text in transifex in the other languages
Screenshot?
<img width="1309" alt="Bildschirmfoto 2022-03-04 um 08 21 10" src="https://user-images.githubusercontent.com/52459078/156718032-d5fa18af-d297-4288-9c0d-e8818940f555.png">

**Comment by Rineee** [comment]
@hello-kathi We changed the wording, so now its a different string and unfortunately you will have to add the translations again once pushed to transifex..

**Comment by hello-kathi** [comment]
@Rineee Ok i will do, let me know when it is there :)
