### ISSUE TITLE
comments_async/comment/edit-menu: spacing div makes mobile design look a bit off

### ISSUE THREAD

**Issue by khamui** [liqd/a4-opin#2472]
**URL:** 
**user:** 
**expected behaviour:**  comments should have equal padding left and right
**behaviour:** edit button (three dots) exceeds on right side
**important screensize:**
**device & browser:** 
**Comment/Question:** 
To be changed in a4, therefore to be checked in mB and aplus as well

Screenshot?
<img width="314" alt="Bildschirmfoto 2022-03-10 um 11 40 17" src="https://user-images.githubusercontent.com/52801593/157655607-a277cc77-1539-4f89-b622-e0a3fc5c7b27.png">

**Comment by phillimorland** [comment]
@khamui just a heads up incase you're working on this, doesn't need to be done in a4, will adapt css in opin
