### ISSUE TITLE
Add users who participate in a public project to the list of participants

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#403]
By this we could:
- offer an option to make a public project private (excluding all who have only read before)
- easier send messages/emails to all users who interacted with the project
- have a better definition of 'participants' in public projects: instead of 'all users' participants of a project would be only those who actually participated in the project

**Comment by rittermo** [comment]
@MagdaN I think it makes sense! We will have a notification user story in the next sprint, and we should think about it in that context. We should discuss this question in our next weekly.

**Comment by slomo** [comment]
Since we have now the follow feature, we probably don't need this anymore?
