### ISSUE TITLE
(Mobile) Make it possible to close timeline description

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/a4-opin#434]
Hi all, as seen this morning, it is a bit tricky for users to close the description of the pop-up phase description in the timeline. If it would be like on desktop so that users click anywhere and the pop-up disappears or there would be a "x" for closing, that might be helpful. Thanks :) 

![img_2681](https://cloud.githubusercontent.com/assets/13625047/19926767/c39a8614-a0f6-11e6-83e0-28df80fb22a5.PNG)

**Comment by SabineJulia** [comment]
You can click anywhere and the pop-up closes now.
