### ISSUE TITLE
Refactor Follows API

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#510]
The Follows-API is working nicely but I think it is implemented rather complicated:
1) not restful in the sense of  the DRF
2) use PUT to create (with a custom mixin)
3) #507

This makes it hard to understand the code to others and also is implemented differently then all the other API-Endpoints

Instead I would suggest to just have a Follows list, that allows POST. When the Follow-Button in the React-Component is clicked, it sends a POST-Request to the Followlist (includes the project and the enabledflag) -> there the create function checks if an entry for a current user already exists, if not it creates one, if yes it updates the existing one. 

The initial value is added to the react component when it is called in the template tag, no GET request is needed.

@slomo what do you think? Would that work or did I miss something?

**Comment by slomo** [comment]
I see your point and but decided more or less deliberately for the current design, but I am open for improvements:

A few arguments from my point of view:

  - #507 is not related to the API
  - using PUT for created by using this mixin is a recommendation from the [DRF documentation](http://www.django-rest-framework.org/api-guide/generic-views/#put-as-create)
  - the current API keeps the logic in the API more complex and the client therefore simpler

**Comment by MagdaN** [comment]
I think the most complicated part is the URL design as it is not visible in the router that you are using a slug, but then the slug is magically added. I can understand that you want to avoid query parameters but as this url is not visible to users I think query parameters are ok.

For further development we should decide which way to go, because, I think, it is also confusing to use different approaches inside one API. If we decide to stick to this we should consider to refactor the other Apps (e.g. reports)

**Comment by SabineJulia** [comment]
related to #629

**Comment by phillimorland** [comment]
this is ref in follow issue but this is bit general for current level of development so will close
