### ISSUE TITLE
Placeholder/Fallback for Organisation Logo

### ISSUE THREAD

**Issue by damusp** [liqd/a4-opin#616]
I suggest using the OPIN-exclamation mark for this one

![organisation_logo_placeholder](https://cloud.githubusercontent.com/assets/22769111/22203134/d58db458-e16b-11e6-9ab2-55db2d420acc.png)

**Comment by vellip** [comment]
I don't think this is desirable, @damusp.

**Comment by damusp** [comment]
Placeholder logos will never be desirable!
I'm open for suggestions though (except if flightless birds are involved)

**Comment by SabineJulia** [comment]
@rittermo @gereonrahfeld what do you think? is the OPIN logo ok as a placeholder or should we change it?

**Comment by gereonrahnfeld** [comment]
From my side it's fine. Let's leave it as it is.
