### ISSUE TITLE
Link from Edit Project to User Management

### ISSUE THREAD

**Issue by damusp** [liqd/a4-opin#623]
A connection between these two would be very useful. 

Could look something like this: 

![dashboard_offlinephases](https://cloud.githubusercontent.com/assets/22769111/22244198/e4b8d024-e22a-11e6-92c1-e4bf84fe06f5.png)

**Comment by damusp** [comment]
Should we have one for the other way round as well? 
So you can get from user management to project editing just as easily.

**Comment by rittermo** [comment]
@damusp Great idea, I would be for it!
It also shows how closely user management and the project settings are connected. We may have reached the limits of keeping our three-tabs interface from the frontend for the dashboard. But this is stuff for the future.

**Comment by slomo** [comment]
I have this working locally. But I have a general question, which also affects the offline phases edit button. Putting a button inside a from, that will make you leave the page and loose form state, is that really a good idea?

**Comment by MagdaN** [comment]
Where else would you put it?

**Comment by SabineJulia** [comment]
I would suggest to clarify what the symbols in the project list mean by adding wording below? I think that this way it might be more clear for initiators where to find the user management. This seems to me like an the easiest solution. What do you think?
![re_ fwd_ fwd_ requests regarding opin](https://cloud.githubusercontent.com/assets/24652917/26318063/1782f29a-3f1a-11e7-8ab9-dbf6434f68ee.jpg)

**Comment by slomo** [comment]
> I would suggest to clarify what the symbols in the project list mean by adding wording below?

I think the idea of this issue is to improve the visibility/reachability directly from the project form. What you propose could also be interesting, but would be something different. The meinBerlin dashboard does exactly this:

![meinBerlin dashboard](https://image.prntscr.com/image/d042096ddb16410baf6c595e0550c9d3.png)

**Comment by slomo** [comment]
Okay, what is the status here? I would recommend to just drop it and say that the dashboard rewrite will fix this issue.

**Comment by damusp** [comment]
Indeed!
