### ISSUE TITLE
dashboard: show blueprint name instead of module name

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#625]
In the project list for organization owners, we currently show the module of a process. I think with our new, hopefully more understandable, blueprint names, we should show the name of the blueprint instead.

![bildschirmfoto 2017-01-24 um 13 07 49](https://cloud.githubusercontent.com/assets/15341015/22246730/7cf2b98a-e236-11e6-8041-5ba6dbdb5777.png)

**Comment by slomo** [comment]
We can't show the blueprint name there, because it is not saved which blueprint created an project. Which leaves us with two options here:

1. We could go through the blueprints and match which one matches the most
     - What should we do with setups that don't match any blueprint?
2. We could store the blueprint.
     - What should we do if the blueprint is modified/deleted. Because in that case it wouldn't match the blueprint specification anymore.

**Comment by MagdaN** [comment]
I would go for 2. but only display the name if it matches an existing blueprint.

**Comment by slomo** [comment]
Isn't that like super confusing if that blueprint has been modified?

**Comment by MagdaN** [comment]
The other team would also be interested in this feature, they would go for solution 2 as blueprints probably are not editable. When we make blueprints editable, we can save a reference, as they are in the database then.

**Comment by SabineJulia** [comment]
converted into User Story
