### ISSUE TITLE
follow count shows zero if logged out

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#629]
The follower count in projects, as shown on the project detail page, goes to zero if you are not logged in. We should show the real number even for users who are not logged in. 

<img width="701" alt="bildschirmfoto 2017-01-24 um 23 53 58" src="https://cloud.githubusercontent.com/assets/15341015/22270589/9226f6a4-e290-11e6-9e8c-989e61211da2.png">

**Comment by gereonrahnfeld** [comment]
still not solved

**Comment by phillimorland** [comment]
closing in favour of https://github.com/liqd/a4-opin/issues/1086
