### ISSUE TITLE
Make it more clear when rating is not active

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#641]
During the user testing session in Rome, it was very confusing to people when rating was available and when it wasn’t. We should show the difference more clearly. If need be, we should even write a small status message underneath the rating indicators, that rating is not active in the current phase.

**Comment by rittermo** [comment]
@damusp Could you come up with an idea for this? Thank you!

**Comment by damusp** [comment]
I can totally relate to this. I think it's important to clarify when rating is disabled. 
Still, I think it should be rather subtle. A written message might be too distracting, but it could pop up when a disabled button is being clicked. 


![inactiverating_message](https://cloud.githubusercontent.com/assets/22769111/23892614/9cc36c1a-089b-11e7-9180-a91974403ac4.png)


What do you think?

**Comment by damusp** [comment]
revisited this just now and realized that the difference between active and inactive is actually a bit too subtle. 

I'd rather go for something stronger:

![inactiverating_message2](https://cloud.githubusercontent.com/assets/22769111/23907985/fb2fedf0-08d2-11e7-94b6-0c7c5cdbb2f5.png)

**Comment by slomo** [comment]
We can solve the styling in opin. The Popup probably requires changes in adhocracy4. Would that change affect also rating buttons for comments?

**Comment by damusp** [comment]
Yes, ideally all rating buttons should follow the same rules.

**Comment by gereonrahnfeld** [comment]
Does this also count for the display of how many rating were given in the list view?

**Comment by SabineJulia** [comment]
![grafik](https://user-images.githubusercontent.com/24652917/33021877-98c2be8a-ce03-11e7-900c-559542992453.png)

**Comment by slomo** [comment]
So the discussion in the thread was only about the widget it self so far. But it should (maybe) also include the listing.
