### ISSUE TITLE
refactor offline phase dashboard js

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#644]
1) ~~check if transition between local time in FE and UTC in BE is working~~ (moved to #827)
2) use empty_form https://docs.djangoproject.com/en/1.10/topics/forms/formsets/#empty-form

**Comment by fuzzylogic2000** [comment]
In ka-2017-05-user-timezone-datepicker, there are no fields to insert a date when I create the offline phase. but only when I edit it.

**Comment by hello-kathi** [comment]
@phillimorland Don't know what that is :) Please lable with reminder if it is important or close.

**Comment by phillimorland** [comment]
seems to work now
