### ISSUE TITLE
Introduce pip-tools for better requirement pinning

### ISSUE THREAD

**Issue by slomo** [liqd/a4-opin#652]
[pipenv](https://github.com/kennethreitz/pipenv/blob/master/README.rst) aims to improve python package management by combining virtualenv and pip into a single utility. It also introduces a new feature for freezing all deps for production deployments.

I think it would improve our workflow and improve our deployments so we should consider using it. But we could maybe use OPIN first as a test platform.

@xi @2e2a I would also be interested in your opinion.

**Comment by xi** [comment]
> Pipenv is an experimental project -- http://docs.pipenv.org/

> WARNING: This project is under active design and development. Nothing is set in stone at this point of time.  -- https://github.com/pypa/pipfile

sounds like it is a bit early to adopt this. Apart from that, it seems like a good idea.

**Comment by slomo** [comment]
@xi You are probably right. I was looking for alternatives, eg [pip-tools](https://github.com/nvie/pip-tools). What do you think about pip-tools?

**Comment by xi** [comment]
Looks good, especially because it just adds tooling around the existing requirements.txt format. In the long run, pipfile may actually be the better approach, but for now, pip-tools looks like a viable solution.

**Comment by SabineJulia** [comment]
is not important to fix now
