### ISSUE TITLE
Document serializer

### ISSUE THREAD

**Issue by slomo** [liqd/a4-opin#656]
1. Currently documents aren't clean if they are created through the serializer. Should we change this?
2. I suspect that the document serializer doesn't properly set the created_date field

**Comment by MagdaN** [comment]
1) same problem as always - should we call clean in the save method? Maybe we should find a final solution here
2) setting the created field is taking care of in the save method of the TimeStampedModel, so it is properly set

**Comment by slomo** [comment]
There is a user story in the technical backlog for the clean issue. So close for now?
