### ISSUE TITLE
Offline Documentation: Back to project page

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#706]
When I edit the offline documentation of an offline phase, I sometimes want to check how it looks for the participants. Can we add a link to the page that brings you to the participants’ view of the documentation? And if so, would it even be possible to make that page visible even though the phase is not yet active? That would make it almost like a preview page. If this is too much work, please tell me and I make a user story out of it. It is kind of on the verge between user story and issue.

**Comment by MagdaN** [comment]
@rittermo we could add a detail view that is only accessible for moderators, but this is not a preview as the data needs to be saved. Another Idea would be to do this together with the plan to switch between phases, then we could simply display the phase view.

**Comment by SabineJulia** [comment]
converted into user story
