### ISSUE TITLE
clicking on notification links brings you to wrong opin language

### ISSUE THREAD

**Issue by slomo** [liqd/a4-opin#712]
When clicking on a notification link, you will end up seeing opin in the same language as the creator of the notification.

**Comment by MagdaN** [comment]
What would be the solution here, we don't know what language the receiver of the email would prefer. We could add this information to the user settings or always use english.

**Comment by slomo** [comment]
Either use english or store/take language from Profile

**Comment by MagdaN** [comment]
@rittermo @NadineKarbach if we want to go for the solution, to set the language preferences in the user settings, please create a userstory

**Comment by rmader** [comment]
Should we adapt to A+ here?
