### ISSUE TITLE
Online/Offline | Link back to project is missing

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/a4-opin#732]
Hey there, when uploading documents in the offline-phase, a link back to the project would be helpful. Currently, initiators would need to go through their organization and search for the project again, that might be a bit unhandy. 

![bildschirmfoto 2017-03-07 um 10 48 51](https://cloud.githubusercontent.com/assets/13625047/23664955/687607ea-0357-11e7-932f-b937b1f886a3.png)

**Comment by MagdaN** [comment]
Thats the same issue as #706
