### ISSUE TITLE
Dashboard | Better UI solution for language tabs needed

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/a4-opin#736]
Hey there, Mr Koopmann from the City of Elmshorn was slightly confused: He changed the text and saved the changes and could not see the changes effectively on productive. We found out that he changed it in the "EN"-language-section and not in the "DE" language section. It also took us a while to discover this at all. Maybe we can think about a nice UI-solution for users, so that they find the relationship between the changes in the text and the language responses? I post this here as an agreement with @slomo so that we dont loose this incident. 

![bildschirmfoto 2017-03-08 um 11 24 25](https://cloud.githubusercontent.com/assets/13625047/23705536/9428b438-040a-11e7-894d-8e1ae52d7cf7.png)

**Comment by SabineJulia** [comment]
converted into user story
