### ISSUE TITLE
bad contrast in language dropdown

### ISSUE THREAD

**Issue by damusp** [liqd/a4-opin#745]
Orange/Yellow aren't fit to be used as text colour. 
Let's change it to the regular text color (like in all other dropdowns)

<img width="525" alt="bildschirmfoto 2017-03-10 um 09 53 43" src="https://cloud.githubusercontent.com/assets/22769111/23788951/208f5e3a-0579-11e7-8c27-4d517ed3a27c.png">

**Comment by slomo** [comment]
Can we also remove the horizontal lines, which are only present in this dropdown?

**Comment by damusp** [comment]
Good point, I agree!
