### ISSUE TITLE
Create project | Add explanatory text as help to fill in the mandatory fields

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/a4-opin#750]
Hey there, to give initiators a better idea what to fill in before publishing their project, a small sentence would be helpful to have on top, e.g. above "Project settings".
The sentence could be: "Please fill in all obligatory fields, marked with a "*" before you publish your project. Missing obligatory fields will generate a red dot on top of a section where information are missing". (Just a proposal). Thanks! 

![bildschirmfoto 2017-03-13 um 17 24 34](https://cloud.githubusercontent.com/assets/13625047/23864514/0c6e6c74-0813-11e7-83a2-a4d79d36bece.png)

**Comment by slomo** [comment]
We could also replace the `*` by `(required)`. Also in general I would it is a well known design pattern that form fields `*` with are required, at least for me.

**Comment by slomo** [comment]
Fixed
