### ISSUE TITLE
from live website: Saving profile settings page generates error 500

### ISSUE THREAD

**Issue by simonblund** [liqd/a4-opin#773]
T7P5L5-Triage: T5P1L5
From live website: Saving profile settings page generates error 500 but changes are saved.
To reproduce:
1) Create profile with facebook
2) When signed in directly afterwards go "account settings"
3) Fill in form
4) Click save
--- Redirects to error 500 page ---
User agent
Chrome Version 56.0.2924.87 (64-bit) on Mac OS

**Comment by slomo** [comment]
Thank you for your report. I can't reproduce this. Could it be that there is some relation to a specific field value you have set?

**Comment by slomo** [comment]
@simonblund Closing now, because I can't reproduce it. Feel free to reopen if you still have that issue.
