### ISSUE TITLE
URL rediect via next

### ISSUE THREAD

**Issue by mkind** [liqd/a4-opin#780]
It is possible to use the `next` parameter to redirect to arbitrary URLs.  

Consider an opin instance at localhost. The following query:

`http://localhost:8000/accounts/signup/?next=http://liqd.de`

results in the following activation link:

`http://localhost:8000/accounts/confirm-email/NA:1cvnil:0WG4Eq_aB8U-J2U_gMi9VJzAiD8/?next=http://liqd.de`

After activating the account, the redirect is done to `http://liqd.de`.

**Comment by slomo** [comment]
I think the fault lies within the [allauth adapter](https://github.com/liqd/a4-opin/blob/master/euth/users/adapters.py#L24). We should either call sanatize next or at least check if the URL is safe.
