### ISSUE TITLE
ValueError with datetime

### ISSUE THREAD

**Issue by mkind** [liqd/a4-opin#782]
Editing a project and storing phase with invalid date format result in a `HTTP 500`.

```
...
-----------------------------162681784014790862415159440
Content-Disposition: form-data; name="phases-0-start_date"

2017-04-09 10:00
-----------------------------162681784014790862415159440
Content-Disposition: form-data; name="phases-0-end_date"

foobar
...
```

It results in a `ValueError` with ` time data '\rfoobar' does not match format '%Y-%m-%d %H:%M'` at `euth/dashboard/templates/euth_dashboard/includes/project_form_participation_tab.html, error at line 31`

**Comment by SabineJulia** [comment]
fixed in userstory about timezones.
