### ISSUE TITLE
Scrolling down the account setting drop down menu does not work on opin-stage

### ISSUE THREAD

**Issue by SabineJulia** [liqd/a4-opin#783]
Hence, I couldnt log out until I minimized my screen. Though I doubt someone will have as many organisations listed except the admins;) 

![grafik](https://cloud.githubusercontent.com/assets/24652917/24953839/29095d40-1f7d-11e7-86b3-dcd8baf5048b.png)

**Comment by slomo** [comment]
As you have suspected, it was never planned that a user can have that many organisations. I would propose that only show 5 (or any other small number) and instead add an organisations list to the dashboard. But that can't be solved in an issue. We'll need a proper story with design.

Maybe @damusp has alternative solutions to that issue.

**Comment by damusp** [comment]
As @SabineJulia suggested in the title, being able to scroll inside the dropdown would be an easy and expectable solution for this problem. If we set the max height of the dropdown to around, let's say, 350px, everything will stay accessible.

Here's a quick draft:




![userdropdown_01](https://cloud.githubusercontent.com/assets/22769111/25221878/f0ad903e-25b6-11e7-855e-62647cd8b6ab.png)

**Comment by SabineJulia** [comment]
converted into user story
