### ISSUE TITLE
Re-moving archive flag is confusing

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#797]
If I try to remove projects which are achived from the archive (for example, if I mistakenly archived a project or want to re-activate it), there is no button for it. Clicking „unpublish“ works, but this is confusing. We should add an remove from archive button or something like that.

For an example, go here: https://opin-dev.liqd.net/de/dashboard/projects/sdfsdfsd/

**Comment by mkind** [comment]
Is this fixed now?

**Comment by rittermo** [comment]
It is confusing that for de-archiving the project, the same icon is used. Since we do not use labels for the buttons, this is a bit problematic. But maybe we can fix this later, @damusp, once we have thought about a dashboard overhaul?

**Comment by mkind** [comment]
> Since we do not use labels for the buttons, this is a bit problematic.

For now, text is only shown on hovering over the icon.

**Comment by damusp** [comment]
I agree that this is not ideal. A dashboard overhaul would fix this, but it may take a while until that happens. 

Maybe it's ok to wait, but if we want to find a temporary solution I would be thinking about something like a dropdown (screenshot from marvel): 
<img width="212" alt="bildschirmfoto 2017-05-19 um 09 21 21" src="https://cloud.githubusercontent.com/assets/22769111/26237306/e63919d2-3c74-11e7-8997-89ca85136893.png">
All actions are very clear and well explained here, even with using little space.
