### ISSUE TITLE
Dashboard: Show more clearly if project is archived

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#798]
When I want to edit a project which is archived in the dashboard it is not clear to me that this is an archived project. I can only guess it from the button, although not at the moment (see issue #797 for this) Adding a title or label that indicates the status clearly somewhere is necessary.

![bildschirmfoto 2017-04-21 um 13 52 04](https://cloud.githubusercontent.com/assets/15341015/25276354/04e313ba-269a-11e7-96fe-7cda643df960.png)
(This is an archived project, but you wouldn't know)

https://opin-dev.liqd.net/de/dashboard/projects/sdfsdfsd/

**Comment by mkind** [comment]
Is this fixed so far?

**Comment by rittermo** [comment]
This looks fine now! Thank you!
