### ISSUE TITLE
Dashboard list if no archived project looks broken

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#799]
![bildschirmfoto 2017-04-21 um 13 55 29](https://cloud.githubusercontent.com/assets/15341015/25276448/93ba0044-269a-11e7-92db-63ffdb71141c.png)
If there is no archived project, the UI of the list view in the dashboard looks broken. Also the message „No projects created“ is misleading. Either we should fix this view or –even better – we should prevent de-activate the select filter for archived projects if there aren’t any.

**Comment by mkind** [comment]
Should be fixed now.
