### ISSUE TITLE
Piwik is not working

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#800]
Piwik does not track opin.me anymore. Since January it gives me zero visits for the site.

**Comment by slomo** [comment]
@treba123 Can you checkout what is happening here?

**Comment by treba123** [comment]
Alright, was just an issue with the cronjob processing the data for the graphs. All data is there and got processed now.

**Comment by rittermo** [comment]
Hello @treba123,  I think the issue is still not fixed :/

<img width="1274" alt="bildschirmfoto 2017-05-04 um 12 41 09" src="https://cloud.githubusercontent.com/assets/15341015/25700237/1345d7d0-30c7-11e7-8a4d-916d23926c42.png">
<img width="1269" alt="bildschirmfoto 2017-05-04 um 12 40 56" src="https://cloud.githubusercontent.com/assets/15341015/25700239/14f63bb0-30c7-11e7-8fda-0d5f84a55ca0.png">

**Comment by treba123** [comment]
Yeah, you are right. Sorry for that one, now it's finally working :)
