### ISSUE TITLE
Archive: Positioning and styling of the status filter looks awkward

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#805]
I think the positioning of the status filter in the project list view looks strange to me. if you look at list views of ideas, we normally put the filter at the right-hand side and the styling looks different. Why did we change this for the status filter? 

![bildschirmfoto 2017-04-25 um 15 10 50](https://cloud.githubusercontent.com/assets/15341015/25387025/9c8a59c6-29c9-11e7-8b33-bc7583d9bb71.png)

**Comment by rittermo** [comment]
Was this intentional, @damusp ?

**Comment by damusp** [comment]
No – all filter and sorting elements should of course have the same styling. Our old sorting UI should be replaced by the filter bar. 

However, the filter being positioned left while sorting is positioned right was fully intentional.

**Comment by slomo** [comment]
So this is a feature request to update the UI of the already existing views with sort?

**Comment by rittermo** [comment]
Okay, I created a new US for this https://tree.taiga.io/project/evpa-euth/us/1110?no-milestone=1

Could you provide the design/information in the US, @damusp ? Thank you!
