### ISSUE TITLE
Archive: Show message if there is no project

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#806]
If there is no archived (or no active project, for that matter) we just show an empty page. Could we show a nice, centered message that reads: „No projects were found“ 

![bildschirmfoto 2017-04-25 um 15 14 24](https://cloud.githubusercontent.com/assets/15341015/25387165/23f8717c-29ca-11e7-9858-bdcd2aaccccc.png)

**Comment by slomo** [comment]
Thinking about it the message in dashboard is probably also confusing (saying that there are no projects, rather than no projects with that filter). Also it hides the filter if there are no matches. As result one can not disable filter that result in an empty list of projects.
