### ISSUE TITLE
Archive: Archived projects are shown in recent project carousel

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#807]
Archived projects are shown in the recent projects carousel on the homepage. For real life use cases, it should happen not too often that projects are both new and archived, however it can happen in times when not a lot of new projects are created on OPIN. Please exclude archived projects from recent projects, as we only want to showcase new and active projects there.

**Comment by slomo** [comment]
Already implemented (but in A4). Needs update to newest A4 version.

**Comment by SabineJulia** [comment]
is already implemented
