### ISSUE TITLE
Archive: filter option is not shown anymore in the dashboard of the initiator when projects are all archived

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#815]
If an organisation has one project and one archives this project in the initiator's dashboard there is only the button 'create a project' left. No possibility anymore to sort by filters and thus no possibility to get back to the archived project. Could we please change this to the sorting option being always available?

![bildschirmfoto 2017-05-11 um 17 10 54](https://cloud.githubusercontent.com/assets/15954895/25957605/099103ce-366f-11e7-98e3-444ad80b8062.png)

**Comment by gereonrahnfeld** [comment]
also: when there is only the create a project button left and I create a new project it shows me the error 500 after wanting to submit and publish it.

**Comment by mkind** [comment]
> it shows me the error 500 after wanting to submit and publish it.

I am not able to reproduce it. If this remains an issue, I am looking forward to more details (e.g. which project type did you submit)
