### ISSUE TITLE
On opin.me I get an info about not using development build of React

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#819]
![bildschirmfoto 2017-05-16 um 14 23 40](https://cloud.githubusercontent.com/assets/2905743/26105685/4c543df2-3a43-11e7-863c-ea39dc501dbb.png)

It says: This page is using the development build of React. 🚧

Note that the development build is not suitable for production. 
Make sure to use the production build before deployment.

And links to here: https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build

**Comment by SabineJulia** [comment]
should be fixed together with #558

**Comment by mkind** [comment]
done in 3be3374c22c4119ae7bf80cc6a55060ecebae293
