### ISSUE TITLE
Dashboard: Dropdown has wrong order of buttons

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#824]
When editing a project in the dashboard, the first option in the dropdown button is to de-publish the project. The first option should be to save and publish the project instead.

See here: https://opin-dev.liqd.net/de/dashboard/projects/test/

![bildschirmfoto 2017-05-18 um 09 40 41](https://cloud.githubusercontent.com/assets/15341015/26191519/776f7cf6-3bae-11e7-8932-feb18f894da4.png)

**Comment by SabineJulia** [comment]
is already fixed
