### ISSUE TITLE
Error when one clicks on 'Sondage mobile' in the French Version

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#829]
Carmen told us about an error on the French version of Opin platform. When you go to the 'Tester Opin' header you'll find three different fields one can click on. Click on 'Sondage Mobile' and there will be an error notification. Also: this error notification is in English while the headers are again in German although this happens when coming from the French version of Opin.

**Comment by slomo** [comment]
This is a link in the French version of the CMS pointing to a German version of a non-existing a project. Needs to be fixed in CMS.
