### ISSUE TITLE
Can't save documents as normal initiator

### ISSUE THREAD

**Issue by vellip** [liqd/a4-opin#844]
Upon trying to do so, I get a 403 with my API call. I believe this was tested only as super-admin. This was noticed on stage.

**Comment by slomo** [comment]
Do you have link for that document?

**Comment by slomo** [comment]
I was able to reproduce the error locally and fixed it on staging. @gereonrahnfeld @rittermo @SabineJulia Should I deploy it directly to production?

**Comment by slomo** [comment]
This is the fix by the way https://github.com/liqd/a4-opin/commit/66e4db39432cbb734e696927942ea473f6445d5c.

**Comment by slomo** [comment]
Same issue was also present for update. Fixed it in 058a0ab1f43a482b048c701622f746bef8f886d1. Also deployed to stage.

**Comment by gereonrahnfeld** [comment]
@slomo @rittermo @SabineJulia    I think it would be good to directly deploy it to production. Yes.

**Comment by slomo** [comment]
Done
