### ISSUE TITLE
Projects that are in draft, appear in project list of organisation and are clickable.

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#846]
when I choose the organisation agenzija zghazagh on opin.me I see two projects.
As soon as I click on them (as a normal user - not admin!) an error 403 appears.

**Comment by MagdaN** [comment]
The reason for this error was, that the projects were in draft. I changed this, but I guess, it is still an issue that you get an 403 when you click on a project that is in draft.

**Comment by slomo** [comment]
This is a regression of https://github.com/liqd/a4-opin/commit/c8df471e3eb1d5739eafa7c73ed980bf5f7a007b, which I probably introduced when including the filters into the view.
