### ISSUE TITLE
Set Guidelines to appear in the middle

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#862]
Guidelines should be flush left but in the middle under the title 'Guidelines'

https://opin-stage.liqd.net/en/help/guidelines/

**Comment by fuzzylogic2000** [comment]
Looks quite centered to me! (Will leave it for now.)

**Comment by slomo** [comment]
I don't understand the issue her, could you provide more detail.

@fuzzylogic2000 If you think that this is resolved, please close the issue.

**Comment by gereonrahnfeld** [comment]
will be solved by new update of navigation.
