### ISSUE TITLE
Set 'Service and Consulting' in the middle 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#863]
The text of 'Service and Consulting' should be flush left but set in the middle under the title 'Service and Consulting'

https://opin-stage.liqd.net/en/help/service-and-consulting/

**Comment by fuzzylogic2000** [comment]
Looks quite centered to me! (Will leave it for now.)

**Comment by gereonrahnfeld** [comment]
Will be solved by new form of guidelines.
