### ISSUE TITLE
Shrink image size in 'Hints and Tricks' section (start project)

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#867]
on English version of staging server:  https://opin-stage.liqd.net/en/start-your-project/

![hints and tricks](https://user-images.githubusercontent.com/15954895/27329531-32752822-55b6-11e7-9b70-ccce081099d2.png)

**Comment by fuzzylogic2000** [comment]
If you shrink the image itself and then include it in the info block, it is also shown smaller.

**Comment by slomo** [comment]
closing now, feel free to reopen if the info should be wrong
