### ISSUE TITLE
notification 'project is over' when it is not over yet

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#871]
When, in a project with three phases, I want to go back from the last (active) phase to a previous one I receive the notification: this project is over.

![this project is over](https://user-images.githubusercontent.com/15954895/27442735-548bd4ee-5771-11e7-9cd9-8d12fee11140.png)

This is not true. Instead we need here the notification that 'this project phase is over'.

![this project phase is over](https://user-images.githubusercontent.com/15954895/27442777-722a07b4-5771-11e7-9436-f0bf37d5c3cd.png)

**Comment by ahmedjenbaz** [comment]
fixed with by sasha https://github.com/liqd/a4-opin/pull/873
