### ISSUE TITLE
Error 500 when creating a new project

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#876]
When I want to create a new project (no matter which template - e.g. Brainstorming) for the organisation ბავშვთა და ახალგაზრდობის ეროვნული ცენტრი (URL: https://opin.me/de/dashboard/organisations/children-and-youth-national-centre/projects/) it shows me an Error 500 when I want to publish it. Publishing and saving it as a draft are not possible. 

![1](https://user-images.githubusercontent.com/15954895/27864139-a277aaf4-618d-11e7-847b-c603696f1376.JPG)

**Comment by slomo** [comment]
Not reproducible anymore, occurred only in older releases.
