### ISSUE TITLE
mixed language email

### ISSUE THREAD

**Issue by xi** [liqd/a4-opin#877]
I just received a mail from opin with the subject "A Kommentar was added to your Kommentar". So the word commont got translated to german, the rest did not. I think translating nothing would be better than translating individual words.

The reason for this behavior could be that "Kommentar" is the verbose name from a model.

**Comment by slomo** [comment]
Already fixed in adhcoarcy4 https://github.com/liqd/adhocracy4/commit/b1dd19799e140503390dcae9aa966a3cc48352cf but requires to update in opin.
