### ISSUE TITLE
the titles of the "help" section don't appear in the translated languages

### ISSUE THREAD

**Issue by SabineJulia** [liqd/a4-opin#914]
The titles on the tiles of the "help" section (productive server) appear translated. When I click on one of the tiles the title appears only in english though. It should appear in the selected language though.
 
![grafik](https://user-images.githubusercontent.com/24652917/29277600-65dbf0d8-8112-11e7-8c71-0bbf73ba7d5e.png)

**Comment by SabineJulia** [comment]
I forgot to send the link:)  https://opin.me/ka/help/guidelines1/

**Comment by gereonrahnfeld** [comment]
fixed, très bon
