### ISSUE TITLE
styling for deletion of comment

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#921]
When I delete my own comment in OPIN I get an unstylish remark where my comment used to be saying: unbekannte*r Nutzer*in deleted by creator. 

Could we restyle this according to how a comment looks like?
unknow user (in blue) + date + deleted by author

![unbekannter nutzer](https://user-images.githubusercontent.com/15954895/29567938-0c43c8f0-874f-11e7-9816-85699b1aae46.png)

**Comment by MagdaN** [comment]
There is not so much that we can do here. We could change the colour of unknown user to blue, but blue indicates a link (to the user profile) which does not exist for an unknown user.

**Comment by slomo** [comment]
Is this really a current sprint issue? It is not related to any stories in the current sprint, or am I missing something.

**Comment by gereonrahnfeld** [comment]
No it is not. But Moritz asked us to do this because it is an issue that has to be fixed in core/ A4.

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld Can we close this issue here? The problem remaining is the missing date, and that will be solved in core at some point?

**Comment by gereonrahnfeld** [comment]
yes, as discussed with Moritz, we will close this issue for now
