### ISSUE TITLE
DST: text in phases section is broken and wrong

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#923]
The texts of the results display in the DST is wrong in the phases section. 

1. Texts should always start with a capital 
2. English and German mix
3. Optional text is wrong (should be: Add offline phases to your online participation)
4. Text und phase two cuts through container

![text_ engl germ_capital letter_ over the margin_wrong text](https://user-images.githubusercontent.com/15954895/29604326-6e3fbfda-87e7-11e7-9f0e-78ae126f9a45.png)

**Comment by mkind** [comment]
@gereonrahnfeld I didn't yet fixed the translation issue of the optional offlinephase text. If this is not blocking, we might open another issue or otherwise I'll translate the text instantly.

**Comment by gereonrahnfeld** [comment]
I think it doesn't block the closing of the issue. We are going to see what strings are missing in transifex during the next weeks - and in this context we'll come back to it.  Will close the issue thus.
