### ISSUE TITLE
Link in email for 'Only a few hours left to participate in <project>' is wrong

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#933]
It is 'https://opin-dev.liqd.net/de/None/projects/rrete/' instead of 'https://opin-dev.liqd.net/de/projects/rrete/'

![bildschirmfoto 2017-08-28 um 12 10 43](https://user-images.githubusercontent.com/2905743/29769297-14d87426-8bea-11e7-9f0a-849aa315d053.png)

**Comment by slomo** [comment]
Already fixed in production
