### ISSUE TITLE
DST: on smaller screens information page is not displayed correctly

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#938]
When I switch to a smaller screen (e.g. width 414) the information page of the DST is only shown to a specific extend (only the left side of it)

![information page doesn t work on smaller screens](https://user-images.githubusercontent.com/15954895/29873067-47daea6c-8d92-11e7-8ba4-27922c353efd.png)

**Comment by slomo** [comment]
There is no mobile support for DST and Dashboard.
