### ISSUE TITLE
add new error for the case that user wants to access private process but is not invited

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#952]
When I want to access a private process without being invited Error 403 is shown. 

![access as not invited user to a project](https://user-images.githubusercontent.com/15954895/31169331-829dcdb4-a8f8-11e7-9f46-df0bb6c340ea.png)

I think it would be better to display an information saying: This is a private project. You need an invitation to take part in it.

**Comment by mkind** [comment]
Hm. Accessing a private project returns a side claiming

> This is a private project. In order to see its content you have to ask the owner for permission to join.

**Comment by MagdaN** [comment]
@mkind thats how it is supposed to be
@gereonrahnfeld do you have the link of that page

**Comment by gereonrahnfeld** [comment]
I cannot reproduce this issue, a.k.a. cannot find the project anymore which gives one the error message. All the other private processes seem to work fine. Thus, will close. and re-open if neccessary.
