### ISSUE TITLE
not possible to access privat process even though I am invited 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#953]
ggr+8 was invited to the project Sondaggio of the organisation Opin Elba. ggr+8 accepted the invitation and is listed as one of its members. 

![bildschirmfoto 2017-10-04 um 11 43 58](https://user-images.githubusercontent.com/15954895/31169633-923b1eb0-a8f9-11e7-8d6e-d8b53b624031.png)

However, ggr+8 is not able to access the project when logged in and receives an error notification

![bildschirmfoto 2017-10-04 um 11 42 35](https://user-images.githubusercontent.com/15954895/31169652-a3bf0e3a-a8f9-11e7-9ecc-c7d2ad4ab18d.png)

**Comment by slomo** [comment]
It seems that the project is not yet published, so not really a problem with the invites.
