### ISSUE TITLE
Dashboard: Blueprint titles and descriptions in English

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#960]
The titles and descriptions of the blueprints in the dashboard are shown in English although I am on the German version of OPIN.

![bildschirmfoto 2017-10-13 um 16 38 59](https://user-images.githubusercontent.com/15341015/31551576-464b2e26-b035-11e7-83f4-b96dc123a40a.png)

**Comment by gereonrahnfeld** [comment]
done - already on dev
