### ISSUE TITLE
When I switch to German in the Blueprint View, the design is broken

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-opin#966]
![bildschirmfoto 2017-10-17 um 15 57 33](https://user-images.githubusercontent.com/2905743/31668987-00ac94c8-b354-11e7-8235-6d153477dc59.png)

**Comment by fuzzylogic2000** [comment]
Because the text on the button is too long! Should we make the text shorter or make it breaking as this could also happen with other languages?

![screenshot from 2017-10-18 08-55-54](https://user-images.githubusercontent.com/8178179/31704685-ac13d19e-b3e2-11e7-978f-79cbbb48fb62.png)

**Comment by gereonrahnfeld** [comment]
What do you mean with 'make it breaking'? I think we cannot guarantee that the text is always short. We have the same problem in the tiles of the help section. Some languages need more space I guess ...

**Comment by fuzzylogic2000** [comment]
I mean that it gets two lines (or more) when it becomes too long.

**Comment by gereonrahnfeld** [comment]
Yes, that would be great.
