### ISSUE TITLE
Delete Maltese from Transifex list

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#967]
As part of US #1456 Maltese (as well as Russian and Ukrainian) should be enabled/ deleted from the range of languages that we offer. In Transifex it is still active. 

![bildschirmfoto 2017-10-17 um 16 12 59](https://user-images.githubusercontent.com/15954895/31669787-52cede44-b356-11e7-988b-75aa575722c8.png)

**Comment by phillimorland** [comment]
@hello-kathi should this still be done?

**Comment by phillimorland** [comment]
already done

**Comment by hello-kathi** [comment]
@phillimorland Top!
