### ISSUE TITLE
Perhaps change the title 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#982]
We also have to think about changing the title of the projects and organisations section - find your project and find your organisation feels a bit clumsy. But it will become changeable in wagtail, won't it?

![screen shot 2017-11-09 at 18 26 45](https://user-images.githubusercontent.com/15954895/32619843-205dc618-c57c-11e7-90cc-2cae3a8f9026.png)

**Comment by MagdaN** [comment]
@gereonrahnfeld no it does not come from wagtail

**Comment by gereonrahnfeld** [comment]
will close for now
